### ISSUE TITLE
Wrong naming of columns

### ISSUE THREAD

**Issue by cbornet** [liquibase/liquibase-hibernate#103]
The following fields
```java
    @OneToOne
    private FooBar fooBar;

    @ManyToOne
    private FooBaz fooBaz;
```
will be mapped as columns fooBar_id and fooBaz_id by liquibase:diff whereas hibernate joins on "foo_bar_id" and "foo_baz_id". A workaround is to explicitely give the JoinColumn name by annotation but it would be better if liquibase could guess it correctly.

liquibase.version : 3.4.2
liquibase-hibernate4.version : 3.5
hibernate.version : 4.3.11.Final
driver : org.postgresql.Driver
referenceUrl : hibernate:spring:com.mycompany.myapp.domain?dialect=org.hibernate.dialect.PostgreSQL82Dialect

It doesn't depend on the DB : seen with both mysql and postgres

**Comment by cbornet** [comment]
A unique constraint should also be set on the OneToOne join column which is not the case at the moment.

**Comment by cbornet** [comment]
OK. Just found out that we could specify a naming_strategy so this solves the naming issue.
The OneToOne uniqueness remains though but it is another issue

**Comment by ouyangshixiong** [comment]
Hope someone can deal with this issue. Thanks
