### ISSUE TITLE
Add <pre-condiftion> when generating changesets

### ISSUE THREAD

**Issue by Nagendra080389** [liquibase/liquibase-hibernate#109]
How do I add `<pre-conditions>` such as `<sqlCheck>, <columnExists>, <tableExists>, <dbms>` while generating the changelogs.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-439) by [Unito](https://www.unito.io/learn-more)

**Comment by filipelautert** [comment]
This is not supported by generateChangelog command in core as per https://forum.liquibase.org/t/how-to-generate-liquibase-change-logs-along-with-basic-preconditions/3587 .
