### ISSUE TITLE
Error when i execute liquibase:diff for generate changelog from JPA entities

### ISSUE THREAD

**Issue by LucasES** [liquibase/liquibase-hibernate#115]
Hi, guys.
I have a Spring boot project with a parent and three children modules.

In my liquibase.properties i have the code:

**changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
url=jdbc:mysql://localhost:3306/bp_vacation
username=root
password=root
driver=com.mysql.jdbc.Driver
outputChangeLogFile=src/main/resources/db/outputChangeLog/liquibase-outputChangeLog.xml
referenceUrl=hibernate:spring:br.com.company.project.domain?dialect=org.hibernate.dialect.MySQLDialect
diffChangeLogFile=src/main/resources/liquibase-diff-changeLog.xml**

So, if i try execute the command: liquibase:diff i receive the error: 

**Failed to execute goal org.liquibase:liquibase-maven-plugin:3.4.1:diff (default-cli) on project company-club-web: Execution default-cli of goal org.liquibase:liquibase-maven-plugin:3.4.1:diff failed: A required class was missing while executing org.liquibase:liquibase-maven-plugin:3.4.1:diff: org/springframework/orm/jpa/persistenceunit/DefaultPersistenceUnitManager
[ERROR] -**

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-442) by [Unito](https://www.unito.io)

**Comment by Nagendra080389** [comment]
I am too having multi modules project. Did you resolve this?

**Comment by LucasES** [comment]
Hi, finally it worked.
In my project i have one module reponsible for the model's, one for service and another for web.
I configured the liquibase in my web module...
So, i add two dependency's: liquibase-core 3.4.1 and liquibase-maven-plugin 3.4.1. And i configured one plugin just like this tutorial: http://www.baeldung.com/liquibase-refactor-schema-of-java-app
Item 6.1.

Finally in my liquibase.properties file i configured just like this:
```
changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
url=jdbc:mysql://localhost:3306/test
username=root
password=root
driver=com.mysql.jdbc.Driver
outputChangeLogFile=src/main/resources/db/outputChangeLog/liquibase-outputChangeLog.xml
referenceUrl=hibernate:spring:br.com.beachpark.vacation.domain?dialect=org.hibernate.dialect.MySQLDialect
diffChangeLogFile=src/main/resources/db/diffChangeLog/liquibase-diff-changeLog.xml
```

**Comment by Nagendra080389** [comment]
Sounds correct. But I cannot move my models to one module. Its a production code. I have almost like 10 modules and the domains are distributed all over. Is there a way in which referenceUrl will accept more than one package to scan from?

**Comment by Nagendra080389** [comment]
I am using hbm scanning as scanning my model throws exception as "org.hibernate.MappingException: Could not determine type for: java.util.List, at table: TEST_METADATA, for columns: [org.hibernate.mapping.Column(tests)] ". But scanning the HBM still does not work as the pojos are distributed. How can I handle this? Any idea?

**Comment by LucasES** [comment]
Hi,
Yes you can put more than one reference model. Follow the example bellow:
`hibernate:spring:com.example.employee,com.example.auction?dialect=org.hibernate.dialect.MySQL5Dialect`

About this problem with List, i really don't know why the liquibase throwed this exception. In my list properties works well with this configurations above

**Comment by MohammadToficMohammad** [comment]
add jpa to liqui maven plugin dependcies

**Comment by sandeepsuvit** [comment]
> Hi @Nagendra080389, finally it worked.
> In my project i have one module reponsible for the model's, one for service and another for web.
> I configured the liquibase in my web module...
> So, i added two dependency's: liquibase-core 3.4.1 and liquibase-maven-plugin 3.4.1. And i configured a plugin just like this tutorial: http://www.baeldung.com/liquibase-refactor-schema-of-java-app
> Item 6.1.
> 
> Finally in my liquibase.properties file i configured just like this:
> 
> ```
> changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
> url=jdbc:mysql://localhost:3306/test
> username=root
> password=root
> driver=com.mysql.jdbc.Driver
> outputChangeLogFile=src/main/resources/db/outputChangeLog/liquibase-outputChangeLog.xml
> referenceUrl=hibernate:spring:br.com.beachpark.vacation.domain?dialect=org.hibernate.dialect.MySQLDialect
> diffChangeLogFile=src/main/resources/db/diffChangeLog/liquibase-diff-changeLog.xml
> ```
> 
> In my project i chosen using a .xml file for the db-master file so i needed configure the application.properties file for read this file:
> 
> ```
> liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
> ```

Hi @LucasES could you also let me know the maven command you executed for this?

Like for example did you execute the liquibase command from the root module or the sub module?

**Comment by filipelautert** [comment]
Seems this has been resolved, closing the issue.
