### ISSUE TITLE
diffChangeLog against mysql schema contains dropNotNullConstraint that subsequently error

### ISSUE THREAD

**Issue by broush-discus** [liquibase/liquibase-hibernate#122]
I ran 
liquibase --changeLogFile=changelog.xml --url=jdbc:mysql://localhost/my_schema ... 
--referenceUrl=hibernate:classic:hibernate.cfg.xml diffChangeLog

the generate change log file contains many instances like
<dropNotNullConstraint tableName="TableName" columnName="ColumnName" columnDataType="int"/>

Next I created a db update script using liquibase updateSQL command which contains many corresponding sql statements like
ALTER TABLE my_schema.TableName MODIFY ColumnName INT NULL;
which yield mysql error
Error Code: 1171. All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead

Using liquibase-hibernate4.2-3.5.jar, liquibase 3.4.2, hibernate 4.2.11, MySQL 5.7, 
mysql-connector-java-5.1.27.jar

Example annotations in the java source file
@XmlRootElement
@Entity
@Table(name = "TableName")
...
	@ManyToOne(targetEntity = XEntity.class, fetch = FetchType.EAGER)
	@JoinColumn(name = "ColumnName")

This looks to me like the liquibase hibernate extension is generating unneeded dropNotNullConstraint elements in the change log xml.

**Comment by nvoxland** [comment]
This is fixed with Liquibase-hibernate 3.6
