### ISSUE TITLE
Hibernate5 - Driver class not specified and could not be determined from the url

### ISSUE THREAD

**Issue by ChanningMorris** [liquibase/liquibase-hibernate#125]
I've got a project that builds without issue using the current Hibernate4 release of this plugin, but when I build the master branch (as of this morning), I get this error:

Error setting up or running Liquibase: liquibase.exception.DatabaseException: java.lang.RuntimeException: Cannot find database driver: Driver class was not specified and could not be determined from the url (hibernate:ejb3:<persistence unit name>)

It's a fairly simply configured project with only a single table, so I'm using Hibernate v5 with both the 4 and 5 versions of this plugin - the only change is the 5 version I'm building locally from the master branch here.

Am I missing something or is this a known issue?

**Comment by nvoxland** [comment]
That should work. How are you running Liquibase? Maven? Ant? Command line? Somehow else?

**Comment by ChanningMorris** [comment]
Maven.

Here's the plugin config in my pom:

`<plugin>
	<groupId>org.liquibase</groupId>
	<artifactId>liquibase-maven-plugin</artifactId>
	<version>3.5.1</version>
	<configuration>
		<diffChangeLogFile>impl/diffchangelog.xml</diffChangeLogFile>
		<changeLogFile>changelog.xml</changeLogFile>
		<driver>com.mysql.jdbc.Driver</driver>
		<referenceUrl>hibernate:ejb3:<persistance object name here></referenceUrl>
		<url>${database.url}</url>
		<username>${database.user}</username>
		<password>${database.password}</password>
		<promptOnNonLocalDatabase>false</promptOnNonLocalDatabase>
	</configuration>
	<executions>
		<execution>
			<phase>test</phase>
			<goals>
				<goal>diff</goal>
			</goals>
		</execution>
	</executions>
	<dependencies>
		<dependency>
			<groupId>org.liquibase.ext</groupId>
			<artifactId>liquibase-hibernate5-3.6-SNAPSHOT</artifactId>
			<version>3.6</version>
		</dependency>
	</dependencies>
</plugin>`

Works fine if I swap back to the current release on the Maven repository by changing that artifact id and version number.

**Comment by nvoxland** [comment]
It looks like moving the liquibase-hibernate5 dependency into the plugin dependencies fixes the issue. 

Like this:
```

 <plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <version>${liquibase.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>mysql</groupId>
                        <artifactId>mysql-connector-java</artifactId>
                        <version>5.1.26</version>
                        <type>jar</type>
                        <scope>compile</scope>
                    </dependency>
                    <dependency>
                        <groupId>org.liquibase.ext</groupId>
                        <artifactId>liquibase-hibernate5</artifactId>
                        <version>3.6-SNAPSHOT</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <diffChangeLogFile>impl/diffchangelog.xml</diffChangeLogFile>
                    <changeLogFile>changelog.xml</changeLogFile>
.................
```
