### ISSUE TITLE
CLOB gets translated to VARCHAR(1)

### ISSUE THREAD

**Issue by tadas-subonis** [liquibase/liquibase-hibernate#127]
I have a field annotated with 
```
    @Lob
    private String data;
```

but it gets detected as 
```
<column name="data" type="varchar(1)"/>
```

I am using hibernate 5.0.9 and SQL Server 2012

Hibernate used to generate a proper DDL

**Comment by tadas-subonis** [comment]
And, obviously, that should be varchar(max)

**Comment by nvoxland** [comment]
This appears to be workigng for me with the current liquibase-hibernate/master code. May have been fixed with an earlier fix
