### ISSUE TITLE
Cannot find database driver: org.postgresql.Driver 

### ISSUE THREAD

**Issue by joshwand** [liquibase/liquibase-hibernate#128]
Hi, I am using maven plugin to do JPA diff, but the plugin seems not to be able to find my database driver:

    $ mvn liquibase:diff
    ...
    Error setting up or running Liquibase: liquibase.exception.DatabaseException: java.lang.RuntimeException: 
    Cannot find database driver: org.postgresql.Driver

I have included postgres in plugin dependencies (and I checked to make sure that jar does include the driver class):

		<plugin>
			<groupId>org.liquibase</groupId>
			<artifactId>liquibase-maven-plugin</artifactId>
			<configuration>
				<propertyFile>src/main/resources/db/liquibase.properties</propertyFile>
			</configuration>
			<dependencies>
				<dependency>
					<groupId>org.liquibase.ext</groupId>
					<artifactId>liquibase-hibernate5</artifactId> 
					<version>3.6-SNAPSHOT</version>
				</dependency>
				<dependency>
					<groupId>org.springframework</groupId>
					<artifactId>spring-beans</artifactId>
					<version>4.1.7.RELEASE</version>
				</dependency>
				<dependency>
					<groupId>org.springframework.data</groupId>
					<artifactId>spring-data-jpa</artifactId>
					<version>1.7.3.RELEASE</version>
				</dependency>
				<dependency>
					<groupId>org.postgresql</groupId>
					<artifactId>postgresql</artifactId>
					<version>9.4.1211</version> 
				</dependency>
			</dependencies>
		</plugin>

liquibase.properties:

    driver=org.postgresql.Driver
    url=jdbc:postgres://localhost:6502/dbname
    username=username
    password=password
    changeLogFile=src/main/resources/db/liquibase-outputChangeLog.xml
    referenceUrl=hibernate:spring:com.foo.bar.entity? dialect=org.hibernate.dialect.PostgreSQL82Dialect

**Comment by joshwand** [comment]
After further experimentation, I realized that this is actually a bug in liquibase-core. I opened a ticket here: https://liquibase.jira.com/browse/CORE-2914

**Comment by l30bravo** [comment]
<plugin>
				<groupId>org.liquibase</groupId>
				<artifactId>liquibase-maven-plugin</artifactId>
				<configuration>
					<propertyFile>liquibase/liquibase.properties</propertyFile>
					<changeLogFile>liquibase/db-changelog-master.xml</changeLogFile>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.postgresql</groupId>
						<artifactId>postgresql</artifactId>
						<version>9.4.1208.jre7</version>
					</dependency>
				</dependencies>
			</plugin>
