### ISSUE TITLE
Build against Java 1.6

### ISSUE THREAD

**Issue by jameskleeh** [liquibase/liquibase-hibernate#132]
Is Java 8 required for Hibernate 5 support?

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-444) by [Unito](https://www.unito.io/learn-more)

**Comment by nvoxland** [comment]
Actually no. Earlier builds had the newest hibernate 5.2 as a dependency which does require Java 8, but I later switched the dependency to hibernate 5.0 and didn't notice that it supports java 1.6. 

The released version was compiled against 1.8, though, so until a new version is released you'll have to build it yourself.

**Comment by jameskleeh** [comment]
Ok @nvoxland thanks for letting me know!

**Comment by filipelautert** [comment]
Now we are using java 11 for Hibernate 6.
