### ISSUE TITLE
3.6: Excessive and invalid re-creation of foreign key, index and unique constraints, plus postgres sequences  (hibernate4)

### ISSUE THREAD

**Issue by edwardotis** [liquibase/liquibase-hibernate#136]
Hello,

 I'm migrating most of this bug report from the grails database-migration plugin to here, after @jameskleeh pointed me here.

 I backed up my old data, and let the grails 2.0.0 data-migration plugin take my existing change logs to recreate my database schema from scratch. The resulting db schema looks correct for all tables, foreign keys, uniques, indexes, sequences, etc. (great!)

Then, I ran dbm-gorm-diff immediately without making any other changes to my code base.
It spits out  600+ lines recreating all my Foreign Key, index and unique constraints, plus postgres primary key sequences.

Then, I tried dbm-update with these 600 lines to see if they could be applied and not be recreated in the future. However, running these changes raises the following exception after 100 lines:

ERROR liquibase - changelog.groovy: changelog_049_recreate_test.groovy::1479746974168-25::myuser (generated): Change Set changelog_049_recreate_test.groovy::1479746974168-25::myuser (generated) failed. Error: ERROR: constraint "FK_b7lh7f3gvmok8q8f8a5i09m05" of relation "my_table" does not exist [Failed SQL: ALTER TABLE public.my_table DROP CONSTRAINT "FK_b7lh7f3gvmok8q8f8a5i09m05"]
Command execution error: Migration failed for change set changelog_049_recreate_test.groovy::1479746974168-25::myuser (generated):
Reason: liquibase.exception.DatabaseException: ERROR: constraint "FK_b7lh7f3gvmok8q8f8a5i09m05" of relation "my_table" does not exist [Failed SQL: ALTER TABLE public.my_table DROP CONSTRAINT "FK_b7lh7f3gvmok8q8f8a5i09m05"]

I investigated in my newly created schema, and the constraint in question was named in the db:
FK_6c1rtv3qh3phfrobas8tdrwxh

And the plugin diff is trying to use this in the changeset:
FK_b7lh7f3gvmok8q8f8a5i09m05

What's even more confusing, is that the plugin was able to generate the correct fk constraint name in 12 changesets leading up this one.

Furthermore,

 The sequence name in the initial generation of the tables is *not* the same name used in the 600 lines of re-created constraints and sequences. The initial sequence pattern is correct. The re-created ones are not following the correct pattern. (See #https://github.com/kaleidos/grails-postgresql-extensions/issues/101)

References:
https://github.com/grails-plugins/grails-database-migration/issues/100
https://github.com/grails-plugins/grails-database-migration/issues/95
https://github.com/kaleidos/grails-postgresql-extensions/issues/101
https://github.com/liquibase/liquibase-hibernate/issues/134

Environment:
grails 3.1.14
runtime 'org.grails.plugins:database-migration:2.0.0'
compile 'org.liquibase:liquibase-core:3.5.3
org.postgresql:postgresql:9.4.1212
postgresql-extensions:4.6.8
compile "org.grails.plugins:hibernate4:5.0.12"
compile "org.hibernate:hibernate-core:4.3.11.Final"
compile "org.hibernate:hibernate-ehcache:4.3.11.Final", {
exclude module: 'ehcache-core'
}
compile("org.jadira.usertype:usertype.core:4.0.0.GA") {
exclude group: 'org.hibernate', module: 'hibernate-entitymanager'
}
//BEGIN spring-security-ui depends on explicit hibernate4:5.0.x
compile 'org.grails:grails-datastore-core:5.0.12.RELEASE'
compile 'org.grails:grails-datastore-gorm-support:5.0.12.RELEASE'
compile 'org.grails:grails-datastore-gorm:5.0.12.RELEASE'
compile 'org.grails:grails-datastore-simple:5.0.12.RELEASE'
compile 'org.grails:grails-datastore-gorm-hibernate4:5.0.12.RELEASE'
compile 'org.grails:grails-datastore-gorm-hibernate-core:5.0.12.RELEASE'
Postgres 9.5
Java 8
Ubuntu 14.04LTS

**Comment by rlangohr** [comment]
I have the same problem using hibernate5 version (3.6) and MySQL.

**Comment by rlangohr** [comment]
Ok, I have a workaround. 
On the one hand the "unique" value was null and on the other it was 'false'. 'false' is here the default value. The was found as different at cause the recreation of the indexes and unique constraints.

I have added these two files to fix that problem.

Feel free to use them.



[bugfix.zip](https://github.com/liquibase/liquibase-hibernate/files/613478/bugfix.zip)

**Comment by edwardotis** [comment]
Thanks, @rlangohr !
Would you be willing to submit a pull request of these changes?

**Comment by AlexandreCassagne** [comment]
@atastrumf Could you create a pull request?

**Comment by r2datical** [comment]
Resolved with PR 223.
