### ISSUE TITLE
hibernate5- envers tables are generated incorrectly

### ISSUE THREAD

**Issue by petri-a-virtanen** [liquibase/liquibase-hibernate#137]
It seems hibernate extension generated envers tables based on their default prefix AUD_, instead it should use prefixed/suffixes defined in persistence.xml:
` 
 <property name="org.hibernate.envers.audit_table_prefix" value=""/> 
 <property name="org.hibernate.envers.audit_table_suffix" value=""/>
`
Becaouse we are using suffix "_auditing" instead of default prefix "AUD_" liquibase tries to drop all our _audited -tables and then creates same tables with AUD_ -prefix

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-447) by [Unito](https://www.unito.io/learn-more)

**Comment by crtk** [comment]
related: #99

**Comment by filipelautert** [comment]
See https://github.com/liquibase/liquibase-hibernate/issues/99#issuecomment-397455025 comment for a fix/workaround.
