### ISSUE TITLE
Unable to generate a unique index

### ISSUE THREAD

**Issue by ebonnot** [liquibase/liquibase-hibernate#144]
I use Hibernate 5.0 and plugin 3.6. 

Whereas it is possible to generate a non unique index with `@Table(indexes = { @Index(name = "idx_my_index", columnList = "my_column") })` : 

```
<changeSet author="root (generated)" id="1466155972816-227">
  <createIndex indexName="idx_my_index" tableName="my_table">
     <column name="my_column" />
  </createIndex>
</changeSet>
```

It is not possible to generate a unique index with `@Table(indexes = { @Index(name = "idx_my_index", columnList = "my_column", unique = true) })`. In this case, I get : 

```
<changeSet author="root (generated)" id="1466155972816-227">
  <addUniqueConstraint columnNames="my_column" constraintName="idx_my_index" tableName="my_table" />
</changeSet>
```

where I would expect : 

```
<changeSet author="root (generated)" id="1466155972816-227">
  <createIndex indexName="idx_my_index" tableName="my_table" unique="true">
    <column name="my_column" />
  </createIndex>
</changeSet>
```

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-453) by [Unito](https://www.unito.io/learn-more)

**Comment by filipelautert** [comment]
This has been fixed on commit c010e7e1cb698fe1a68d90266c794b95d3dd8a5d .
