### ISSUE TITLE
cannot find symbol: liquibase.ext.hibernate.customfactory.CustomClassicConfigurationFactory

### ISSUE THREAD

**Issue by 4levity** [liquibase/liquibase-hibernate#146]
I am using programmatic configuration of Hibernate without an XML configuration file. With  liquibase-hibernate4 , as the liquibase-hibernate documentation states, I create an implementation of liquibase.ext.hibernate.customfactory.CustomClassicConfigurationFactory to pass the Hibernate configuration to Liquibase. However, it appears this interface no longer exists in liquibase-hibernate5. There is a class CustomMetadataFactory, which is utilized by HibernateDatabase, but the comments there indicate that it is only for hibernate:ejb3 configuration (I am not using ejb3).

Is there an alternative method to allow use of liquibase-hibernate5 in a non-ejb environment where Hibernate is configured programatically without an XML file?

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-455) by [Unito](https://www.unito.io/learn-more)

**Comment by 4levity** [comment]
UPDATE: After refactoring my code to eliminate Hibernate 4 Configuration and reading more of the hibernate-liquibase code, I figured that implementing CustomMetadataFactory might work even though it says it's for ejb3. 

In fact it does work, but I could not figure out a straightforward way to set the dialect for the reference database. This is because I am calling HibernateDatabase.setConnection with a CustomMetadataFactory implementation class name, rather than an XML path. In this case, buildMetadataFromPath is not called and therefore createMetadataSources is not called, and the dialect is left at null, which causes later failures.

I worked around it by subclassing HibernateClassicDatabase to add a setDialect() method, but it should be a small matter to make this easier.

Thanks for a very useful library.

**Comment by Iwitrag** [comment]
The documentation still states that we need to extend CustomClassicConfigurationFactory.java, but this class does not exist.

**Comment by filipelautert** [comment]
There is still a static variable poing to it ( https://github.com/liquibase/liquibase-hibernate/blob/f5b9290bd174bdb8962e533e2105a711815d7ab2/src/test/java/liquibase/ext/hibernate/database/HibernateClassicDatabaseTest.java#L25 ), but it is only referenced in commented out code. @Iwitrag seems the documentation needs a fix, could you please tell us where did you see this reference ?

**Comment by Kas-tle** [comment]
In case any poor soul ever tries to do the same thing... I was able to achieve this much more easily by using reflection to set the dialect field... that said there should really just be a method to do this:

```java
package net.paradisu.core.database;

import liquibase.Scope;
import liquibase.ext.hibernate.customfactory.CustomMetadataFactory;
import liquibase.ext.hibernate.database.HibernateDatabase;
import liquibase.ext.hibernate.database.connection.HibernateConnection;
import org.hibernate.boot.Metadata;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.hibernate.cfg.AvailableSettings;
import org.hibernate.dialect.PostgreSQLDialect;
import org.hibernate.hikaricp.internal.HikariCPConnectionProvider;
import org.postgresql.Driver;

import java.lang.reflect.Field;

public class LiquibaseHibernate implements CustomMetadataFactory {

    @Override
    public Metadata getMetadata(HibernateDatabase hibernateDatabase, HibernateConnection connection) {

        final StandardServiceRegistryBuilder registryBuilder = new StandardServiceRegistryBuilder()
            .applySetting(AvailableSettings.CONNECTION_PROVIDER, HikariCPConnectionProvider.class.getName())
            .applySetting(AvailableSettings.DIALECT, PostgreSQLDialect.class.getName())
            .applySetting(AvailableSettings.JAKARTA_JDBC_DRIVER, Driver.class.getName())
            .applySetting(AvailableSettings.JAKARTA_JDBC_URL, "jdbc:postgresql://localhost:5432/database")
            .applySetting(AvailableSettings.JAKARTA_JDBC_USER, "user")
            .applySetting(AvailableSettings.JAKARTA_JDBC_PASSWORD, "password");

        MetadataSources metadataSources = new MetadataSources(registryBuilder.build());
        metadataSources.addAnnotatedClass(net.paradisu.core.database.models.PlayerModel.class);

        try {
            Field dialectField = HibernateDatabase.class.getDeclaredField("dialect");
            dialectField.setAccessible(true);
            dialectField.set(hibernateDatabase, new PostgreSQLDialect());
        } catch (NoSuchFieldException | IllegalAccessException e) {
            Scope.getCurrentScope().getLog(getClass()).severe("Failed to set dialect via reflection", e);
        }

        return metadataSources.buildMetadata();
    }
}
```
