### ISSUE TITLE
What is the difference between Migrate & Update 

### ISSUE THREAD

**Issue by makouk20** [liquibase/liquibase-hibernate#147]
Hello , i didn't understand the real difference between Migrate & update i see the same action :
For my case : 
I have a file Master.changelog.xml which contains : 
<include file=""db.changelog-1.0/> ===> create new table
<include file=""db.changelog-1.1/>
When i excuste update with the changefileLog=Master.changelog.xml or with migrate
it's the same result i see a new table 
But the problem  when i create a rollback the table will be removed and when i want to come back to the tag which contains this table removed it's doesn't come again this table.
So i want to know when I do RollBack and after update or migrate the file excuted why the table doesn't come back .

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-456) by [Unito](https://www.unito.io/learn-more)

**Comment by filipelautert** [comment]
Migrate is the former name of update command, so both should yield the same result.
