### ISSUE TITLE
Custom Naming Strategy

### ISSUE THREAD

**Issue by gbrlcustodio** [liquibase/liquibase-hibernate#153]
What if I want to use my project's custom naming strategy? How could I pass it through liquibase configuration properties?

┆Issue is synchronized with this [Jiraserver Bug](https://datical.atlassian.net/browse/LB-461) by [Unito](https://www.unito.io)

**Comment by JaXt0r** [comment]
Spring also uses another naming strategy than one of liquibase.

**org.springframework.boot.orm.jpa.SpringNamingStrategy**

When I call ```mvn liquibase:diff``` my generated changesets from Hibernate entities won't recognize camelCase as underscore names.

e.g.

Table1.java
```java
@Entity
@Table(name = "table1")
class Table1 {	
  @Column
  String userId;
}
```

db.changeset.yml
```yml
- column:
    name: userId
    type: VARCHAR(255)
```

Controller.java
```java
em.find(Table1.class, 1);
```

Leads to:
**org.h2.jdbc.JdbcSQLException: Field "TABL0_.USER_ID" not found**

**Comment by bajracharya-kshitij** [comment]
I used the following and it worked

    @Entity(name = "table1")
    class Table1 {	
        @Column(name="user_id")
        String userId;
    }

**Comment by MatthieuBlm** [comment]
I found a solution that doesn't use the `@Entity` and `@Column` annotation. It help to keep a better code readability.
I've added these line to my **application.properties** to specify the hibernate naming strategy :

- `spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl`

- `spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl`

I don't know how to set the liquibase naming strategy when using `mvn liquibase:diff` but these above properties do the trick and allow hibernate to understand what liquibase have generated.

**Comment by oguzhancevik** [comment]
Hi @gbrlcustodio, @mdaehnert, @bajracharya-kshitij, @MatthieuBlm 

I found a solution. You can change **referenceUrl** on liquibase.properties

### old version
_referenceUrl=hibernate:spring:com.filemarket.locationservice.model.entity?dialect=org.hibernate.dialect.PostgreSQLDialect_

### new version
_referenceUrl=hibernate:spring:com.filemarket.locationservice.model.entity?dialect=org.hibernate.dialect.PostgreSQLDialect&hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy_


### my liquibase.properties content
```
url=jdbc:postgresql://localhost:5432/file-location-service
driver=org.postgresql.Driver

referenceUrl=hibernate:spring:com.filemarket.locationservice.model.entity?dialect=org.hibernate.dialect.PostgreSQLDialect\
  &hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy\
  &hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

referenceDriver=liquibase.ext.hibernate.database.connection.HibernateDriver
```

**Comment by oguzhancevik** [comment]
> What if I want to use my project's custom naming strategy? How could I pass it through liquibase configuration properties?
> 
> ┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-461) by [Unito](https://www.unito.io/learn-more)

**Comment by oguzhancevik** [comment]
> What if I want to use my project's custom naming strategy? How could I pass it through liquibase configuration properties?
> 
> ┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-461) by [Unito](https://www.unito.io/learn-more)

https://github.com/liquibase/liquibase-hibernate/issues/153#issuecomment-888445027

**Comment by filipelautert** [comment]
As per last comment seems there is a way to do it. Please reopen the issue if it still persists.
