### ISSUE TITLE
Error setting up or running Liquibase: liquibase.exception.SetupException: File does not exist:

### ISSUE THREAD

**Issue by nitishnaidi** [liquibase/liquibase-hibernate#174]
I am using Liquibase Version: 3.4.2 and Apache Maven 3.3.9. 

I have the following set up and file structure : 

master.xml

```
<?xml version="1.0" encoding="UTF-8"?> 
<databaseChangeLog 
  xmlns="http://www.liquibase.org/xml/ns/dbchangelog/1.9" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog/1.9
                      http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-1.9.xsd"> 
	<!-- other previous Releases -->
	<!-- Release v10 -->
	<changeSet id="release_0.0.10" author="Nnaidi">
		<tagDatabase tag="version_0.0.10"/>
	</changeSet>
	<include file="src/main/dbschema/dss.Reminder.0.0.1.sql"/>
	<include file="src/main/dbschema/dss.DeleteUnusedTables.0.0.1.sql"/>
	<include file="src/main/dbschema/dss.ActionPlan.0.0.1.sql"/>
</databaseChangeLog>
```

liquibase is not able find the file `dss.DeleteUnusedTables.0.0.1.sql` alone. I have same setup for other files and are running without issues. 

How to resolve this one?

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-476) by [Unito](https://www.unito.io/learn-more)

**Comment by bitforce** [comment]
I had this annoying issue and this [answer](https://stackoverflow.com/questions/37192931/liquibase-receiving-file-does-not-exist-exception-when-file-exists-for-change) helped me solve it. I don't have to much context form this belated problem; however, if you ran your migration prior to compilation of your source code, then that could explain it. 

In my case, I ran `mvn clean` and recompiled my code so the target folder would contain my newly added changeset.

**Comment by filipelautert** [comment]
Closing this as it is already answered and it's not related to liquibase-hibernate..
