### ISSUE TITLE
Hibernate physicalNamingStrategy class not being recognized when it is on same project

### ISSUE THREAD

**Issue by desiderati** [liquibase/liquibase-hibernate#176]
When the attributes hibernate.physical_naming_strategy and hibernate.implicit_naming_strategy of option "referenceUrl" are configured with classes that are inside the same project being built the following error occurs: "Error setting up or running Liquibase: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.DatabaseException: java.lang.ClassNotFoundException"

But if I move those classes to another project and add a dependency on the current project, everything works fine.

I was looking the class HibernateDatabase to the point the error occurs...

`builder.applyPhysicalNamingStrategy((PhysicalNamingStrategy) Class.forName(namingStrategy).newInstance());`

And tried to instantiate any class defined on the current project, the Class.forName(..) returned ClassNotFoundException. But if I tried to execute with a class defined on any dependency, it worked.

Here is my config parameters

[liquibase-maven-plugin-3.5.4-diff.log](https://github.com/liquibase/liquibase-hibernate/files/1728362/liquibase-maven-plugin-3.5.4-diff.log)

I believe there is a minor problem with the Classpath Loader which not recognize classes inside the same project.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-478) by [Unito](https://www.unito.io/learn-more)

**Comment by desiderati** [comment]
Just to inform more things. If you put a breakpoint on HibernaeDatabase class, on the point the error occurs and evaluate this expression: "Thread.currentThread().getContextClassLoader().loadClass(namingStrategy"), it returns the class without any problem.

**Comment by gdenchev** [comment]
Great, I was having the same problem and can confirm the fix is working. Thanks for your effort!

**Comment by desiderati** [comment]
> Great, I was having the same problem and can confirm the fix is working. Thanks for your effort!

It was fixed in which version?

**Comment by filipelautert** [comment]
HI - seems this has been fixed some years ago. Please reopen the issue if it still persists.
