### ISSUE TITLE
Unable to define different names for databasechangelog and databasechangeloglock tables

### ISSUE THREAD

**Issue by harry12345** [liquibase/liquibase-hibernate#183]
I have two different war files installed in the same application server with the same database and database schema connection. Both war files contain database changelogs.
It is unable to define different names for databasechangelog and databasechangeloglock tables from the code in CDILiquibaseConfig. It seems at startup creation of databasechangelog and databasechangeloglock tables block each other. These tables should be able to rename from the code.
ERROR: relation "databasechangeloglock" already exists

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-481) by [Unito](https://www.unito.io/learn-more)

**Comment by filipelautert** [comment]
I see, class CDILiquibase does not handle renaming of databasechangelog and databasechangeloglock tables names - but there is the defaultSchema that could be used to separate the two database applications.
If you still required this setting I would ask to open a new issue at liquibase project github issue tracker - https://github.com/liquibase/liquibase/issues . Thanks!
