### ISSUE TITLE
Issue after upgrading GRADLE and JAVA

### ISSUE THREAD

**Issue by amarianetti** [liquibase/liquibase-hibernate#185]
I'm using Spring 2.0.0 and Gradle 4.6 with Java 10.
Previous configuration was working before upgrading to Java 10.

```groovy
def db = 'common'

def packageURI
if ('common'.compareToIgnoreCase(db) == 0) {
    packageURI = 'com.entities.common'
} else {
    packageURI = 'com.entities.client'
}

def dbUsername = 'root'
def dbPassword = 'root'
def dbUrl = 'jdbc:mysql://localhost:3306/' + db + '?serverTimezone=UTC&nullNamePatternMatchesAll=true'
def liquibaseReferenceURL = 'hibernate:spring:' + packageURI + '?dialect=org.hibernate.dialect.MySQL5Dialect'

/**
 * Output files
 */
def sqlOutFile = "$projectDir/src/main/resources/db/db.changelog.sql"
def customDiffChangeLogFile = "$projectDir/src/main/resources/db/db.changelog.yaml"

def taskArgs = [
        "--username=" + dbUsername
        , "--password=" + dbPassword
        , "--url=" + dbUrl
        , "--referenceUrl=" + liquibaseReferenceURL
        , "--outputFile=" + sqlOutFile
        , "--changeLogFile=" + customDiffChangeLogFile
        , "--driver=com.mysql.jdbc.Driver"
        , "--referenceDriver=liquibase.ext.hibernate.database.connection.HibernateDriver"
]


configurations {
    liquibase
}

dependencies {
    liquibase "org.liquibase.ext:liquibase-hibernate5:3.6"
}

/**
 * 1) Change Log - compare existing db vs java entities and creates the changelog.
 */
task schemaChangeLog(type: JavaExec) {
    group = "liquibase"
    classpath sourceSets.main.runtimeClasspath
    classpath configurations.liquibase
    main = "liquibase.integration.commandline.Main"

    args taskArgs
    args "diffChangeLog"
}

/**
 * 2) Export SQL - from the changelog generates the set of statements required to update the DB
 */
task schemaExportSQL(type: JavaExec) {
    println packageURI
    dependsOn schemaChangeLog

    group = "liquibase"
    classpath sourceSets.main.runtimeClasspath
    classpath configurations.liquibase
    main = "liquibase.integration.commandline.Main"

    args taskArgs
    args "updateSql"
}
```

This was working.
After upgrading to JAVA 10 I started getting this error:

`[ERROR] [system.err] Unexpected error running Liquibase: URI is not hierarchical`

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-437) by [Unito](https://www.unito.io/learn-more)

**Comment by joost-de-vries** [comment]
We're having the same problem after upgrading to Java 10. Out hibernate-liquibase version is also 3.6. Liquibase version 3.6.2.

**Comment by Vaelyr** [comment]
Would like to see fix for that aswell.

**Comment by PinkieSwirl** [comment]
Glad I found this issue, was just starting to use liquibase and got the same error (also using java 10).

However, development of this plugin seems to be dead? Or is it just frozen since "it works"?

**Comment by muhlba91** [comment]
Same issue here. Is there any intention to fix this plugin or any alternatives? :/

**Comment by jozefmorvay** [comment]
On java 11, same thing happens. I do not understand how gradle works internally, so I can't really fix it myself.

**Comment by henrykaasik** [comment]
Has somebody managed to overcome from this issue? 
@amarianetti @joost-de-vries  ?

**Comment by MarcelJan** [comment]
I notice that when I switch the Java version up from 8 to 11, one of the calls to `classLoader.getResources("")` in  `liquibase.resource.AbstractResourceAccessor::init` starts returning URLs such as 

`file:jar:file:/home/user/.gradle/caches/modules-2/files-2.1/javax.xml.bind/jaxb-api/2.3.1/8531ad5ac454cc2deb9d4d32c40c4d7451939b5d/jaxb-api-2.3.1.jar!/META-INF/versions/9/`

Such an URL does not correspond to an actual folder on the file system (but to a folder within the jar) and as a result the constructor for URI marks it as opaque.

So when the URL is further processed in `FileSystemResourceAccessor::addRootPath` with 
`
    File pathAsFile = new File(path.toURI());
`    
the result is an _IllegalArgumentException/URI is not hierarchical_  exception: the constructor for File can't deal with opaque URIs

**Comment by smacz** [comment]
Same issue here with java 11.
Is it going to be fixed soon?

**Comment by rylitalo** [comment]
I was able to fix this by upgrading to liquibase 3.6.3 in my build.gradle.

runtime('org.liquibase:liquibase-core:3.6.3')

**Comment by kunickiaj** [comment]
Noticed I only get this if the URL doesn't include jdbc: prefix. For example jdbc:hibernate...

However then I hit a NPE bc it is not finding the correct persistence.xml on the classpath. (There are multiple)

**Comment by filipelautert** [comment]
Seems this has been fixed in liquibase-core some years ago. Please reopen the issue if it still persists.
