### ISSUE TITLE
Liquibase unsupported database

### ISSUE THREAD

**Issue by mshafieluru** [liquibase/liquibase-hibernate#189]
I am trying liquibase with unsupported database ExaSol.

It is failing due to following exception

`liquibase.exception.LockException: liquibase.exception.DatabaseException: Feature not supported: user-defined type (DATETIME) [line 1, column 110] (Session: 1613843703712878739) [Failed SQL: CREATE TABLE SCH.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED datetime, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID))]`

It seems it is failing because of DATETIME datatype. I tried with --currentDateTimeFunction as well. Its not working.

Can someone guide me how to fix this

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-435) by [Unito](https://www.unito.io/learn-more)

**Comment by filipelautert** [comment]
This error is coming from the database. As this is not supported liquibase is using a default sql to create DATABASECHANGELOGLOCK , and as this is a foundation method it doesn't honor parameters.
