### ISSUE TITLE
Unsupported property type for generator annotation @CreationTimestamp

### ISSUE THREAD

**Issue by anmolagar** [liquibase/liquibase-hibernate#193]
Hi, i am running into this issue.
Do you have any suggestions for me on how to fix this?

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-431) by [Unito](https://www.unito.io/learn-more)

**Comment by bibibiu2017** [comment]
Any updates on this?

**Comment by filipelautert** [comment]
HI - seems this has been fixed in liquibase-core some years ago. Please reopen the issue if it still persists.
