### ISSUE TITLE
Is this project no longer maintained? 

### ISSUE THREAD

**Issue by svetozar02** [liquibase/liquibase-hibernate#194]
Last update was 2 years ago, list of issues & PRs is growing... Is there a fork that's more active?

**Comment by CountZachula** [comment]
+1

**Comment by hc-codersatlas** [comment]
Any members / contributors able to let us know?

**Comment by oddi3** [comment]
@nvoxland could you please chime in ?

**Comment by littlebeeper** [comment]
+1

**Comment by usharik** [comment]
+500

**Comment by lrkwz** [comment]
Do we all have to "migrate" to [flyway](https://github.com/flyway/flyway)?

**Comment by nvoxland** [comment]
Sorry for the lack of love to this extension lately. I'm working on pulling it into the main liquibase repo so it doesn't get left behind anymore.

**Comment by Syndlex** [comment]
Is there any update on it?

**Comment by nvoxland** [comment]
It's still on the roadmap but hasn't made it to the top yet. 

We've been focusing first on smoothing out the extension management process in general across all our extensions, then we are going to be looking at bringing the most-used/non-beta ones into core.
