### ISSUE TITLE
mvn liquibase:diff set localdate to tinyblob when used on a jhipster project

### ISSUE THREAD

**Issue by MHTaleb** [liquibase/liquibase-hibernate#196]
I recently observed that the liquibase mvn pluging set the changelog of new entities that are of localdate in my jhipster project to tinyBlob while if I use the jhipster entity manager it set them to date,

Is there any issue or there is some way of making liquibase set any localdate field to date in a changeset

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-429) by [Unito](https://www.unito.io/learn-more)

**Comment by Ndumisosizwe** [comment]
@MHTaleb I had the same issue, still don't know where to configure it so it chooses the desired date type everytime i use mvn liquibase:diff . But you can replace the TINYBLOB in your changeset with whatever desired type (e.g DATETIME ) and then re-run the changelog files. I just did a replaceAll in my IDE.

**Comment by MHTaleb** [comment]
I did the same

Le mer. 3 juil. 2019 05:29, Ndumiso Mhlongo <notifications@github.com> a
écrit :

**Comment by filipelautert** [comment]
Seems this issue has been fixed in liquibase-core with some datetime fixes. Please reopen the issue if it still persists.
