### ISSUE TITLE
diff always regenerate index

### ISSUE THREAD

**Issue by binlaniua** [liquibase/liquibase-hibernate#202]
IndexSnapshotGenerator

miss code 

```
when column unique is false then index.setUnique(false)
```

![image](https://user-images.githubusercontent.com/5960462/58340304-197b4980-7e7e-11e9-8d00-eecec2bf28bc.png)

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-426) by [Unito](https://www.unito.io/learn-more)

**Comment by binlaniua** [comment]
https://github.com/binlaniua/liquibase-hibernate/tree/hibernate4

**Comment by binlaniua** [comment]
i have fix the error and fix comment

**Comment by filipelautert** [comment]
Hi - this has been fixed by `handleHibernateIndex` method. Please reopen if the issue persists.
