### ISSUE TITLE
Latest version of liquibase-core is having security vulnerable version of jQuery (jquery-1.11.0.min.js)

### ISSUE THREAD

**Issue by raika-jagdish** [liquibase/liquibase-hibernate#203]
Latest version of liquibase-core (https://mvnrepository.com/artifact/org.liquibase/liquibase-core/3.6.3) is having security vulnerable version of jQuery (jquery-1.11.0.min.js).  Kindly help to update clean version of jQuery.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-425) by [Unito](https://www.unito.io/learn-more)

**Comment by mjeffrey** [comment]
This is reported here:
https://liquibase.jira.com/browse/CORE-3440

**Comment by filipelautert** [comment]
Thanks for the report! It has been fixed in subsequent versions.
