### ISSUE TITLE
Problem with Sequences and MSSQL Database

### ISSUE THREAD

**Issue by michaelp1989** [liquibase/liquibase-hibernate#211]
I use liquibase-core 3.8.0, liquibase-hibernate5 3.8

In my code i use a SequenceGenerator like this:
@SequenceGenerator(name = "seq-gen", sequenceName = "hibernate_sequence", initialValue = 0)

And in the database it is created like this:
![screenshot](https://user-images.githubusercontent.com/55478835/65146651-9bd6dd00-da1c-11e9-8ef3-461d3b0d97cf.png)

And everytime i run the Liquibase update i get an statement:
ALTER SEQUENCE HIBERNATE_SEQUENCE

I debugged the code and saw that this happens because of this ObjectDifferences:
{minValue=minValue changed from 'null' to '-9223372036854775808',
willCycle=willCycle changed from 'null' to 'false',
maxValue=maxValue changed from 'null' to '9223372036854775807'}

In Hibernate these attributes are null, because in the annotation i cannot set them.

Greetings
Michael

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-419) by [Unito](https://www.unito.io/learn-more)

**Comment by rcamposp** [comment]
I'm having this same issue using Postgres + Envers.

**Comment by filipelautert** [comment]
Hi - i believe this has been fixed here -> https://github.com/liquibase/liquibase-hibernate/pull/354 and in some other PR's. Version 4.25.0 should be fine.
