### ISSUE TITLE
Problem in IndexSnapshotGenerator

### ISSUE THREAD

**Issue by MrKuip** [liquibase/liquibase-hibernate#214]
I get always get a diff of my database wrongly when I annotate a hibernate class with @Index(unique=false).

I'm using liquibase-hibernate5-3.8.jar.

The liquibase.ext.hibernate.snapshot.IndexSnapshotGenerator generates an attribute 'unique' with value 'null'. (This is the value of my hibernate configuration)
The liquibase.snapshot.jvm.IndexSnapshotGenerator generates an attribute 'unique' with value 'false' (This is the value of my sql database)

The liquibase.diff.compare.core.DefaultDatabaseObjectComparator will then compare both Index objects and decides that they are different and a sqldrop and sqlcreate statement is genererated.

I think this is a bug.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-416) by [Unito](https://www.unito.io/learn-more)

**Comment by MrKuip** [comment]
I solved my problem by changing file ./src/main/java/liquibase/ext/hibernate/snapshot/IndexSnapshotGenerator.java

The method isUniqueIndex(....) should return false instead of 'null'

**Comment by filipelautert** [comment]
This issue has been fixed by commit https://github.com/liquibase/liquibase-hibernate/commit/a5072de55b2d67cbe5e76464e8a1fd6ebeb2d0d2 .
