### ISSUE TITLE
liquibase 3.8.5, hibernate 5.4.10.Final, spring boot 2.2.4.RELEASE, and hibernate search 6 cause liquibase diff failed. 

### ISSUE THREAD

**Issue by alexis-puska** [liquibase/liquibase-hibernate#222]
Hi, 
I have a project with liquibase 3.8.5, liquiabse hibernate 3.8, spring boot 2.2.4, hibernate 5.4.10 ans hibernate search, i get this error.

[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:3.8.5:diff (default-cli) on project master-hipster-2: Error setting up or running Liquibase: javax.persistence.PersistenceException: Unable to resolve persistence unit root URL: class path resource [] cannot be resolved to URL because it does not exist -> [Help 1]

In jhipster issues i have read that liquibase 3.7 know this error and it's not fixed. How can we configured liquibase to fixe this missing classpath resources ? 

thank's

**Comment by DanielFran** [comment]
You need to downgrade to liquibase <=3.6 like in jhipster

**Comment by DanielFran** [comment]
We hope some help from @liquibase...

**Comment by alexis-puska** [comment]
I’m stuck with this version. I look inside the server side dependencies and you downgrade hinernate to 5.3.X... I used hibernate search orm 6 to dissociate hibernate search and elastic search of lucene I need to use hibernate 5.4.X... if I configure the liquibase configuration with that I get conflict with hibernate search 6 annotation in my domain.

All issue with this plugins comes with the update of spring boot 2.1.X to spring boot 2.2.X. I think they change something in class loader to retrieve the hibernate session. @liquibase I think I’m not the only one with this problem and they look like recursive problem at every spring boot major version.

**Comment by pavankjadda** [comment]
@DanielFran It looks like the @liquibase team is not actively responding to the issues. It's better to switch to https://flywaydb.org/

**Comment by alexis-puska** [comment]
Flyway can be a good alternative, but in the past i used that, and i don't think that can be the diff schama between spring/javax annotation and the current database schema. At this time liquibase can't create the diff but it can create the database changelog on the current schema. with that we can make all thing that flyway do. 

i open a discussion on liquibase forum with this issues, here, and a ticket on her jira, i don't know how many developper works on liquibase at this time. i read that i work's on a major version (4.0.0).

**Comment by pavankjadda** [comment]
@alexis-puska  Do you have Jira ticket link for me?

**Comment by alexis-puska** [comment]
This ticket : 
https://liquibase.jira.com/browse/CORE-3578

**Comment by jgribonvald** [comment]
The problems seems related to that: https://github.com/liquibase/liquibase/pull/927

**Comment by alexis-puska** [comment]
I see that the liquibase maven plugins 3.8.7 version is published, tested and approuved

@DanielFran in a jhipster project the 3.8.7 works !

**Comment by DanielFran** [comment]
@alexis-puska Thanks for information, will update jhipster.

**Comment by alexis-puska** [comment]
Probleme solved with PR : https://github.com/liquibase/liquibase/pull/927
