### ISSUE TITLE
Could not locate hibernate.cfg.xml resource

### ISSUE THREAD

**Issue by eugenio1590** [liquibase/liquibase-hibernate#249]
I installed the Liquibase plugin for Maven/Gradle in my spring boot project. But I get the following error: 

```
Failed to execute goal org.liquibase:liquibase-maven-plugin:3.8.5:diff (default-cli) on project application: Error setting up or running Liquibase: org.hibernate.internal.util.config.ConfigurationException: Could not locate cfg.xml resource [src/main/resources/hibernate.cfg.xml]
```

I am using the **referenceUrl** value: `hibernate:classic:src/main/resources/hibernate.cfg.xml`

How to solve this?

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-406) by [Unito](https://www.unito.io/learn-more)

**Comment by ninaHerpertz** [comment]
Hi, I have the same issue - is there anyting done about it?

**Comment by filipelautert** [comment]
Seems this has been fixed in liquibase-core some years ago. Please reopen the issue if it still persists.
