### ISSUE TITLE
Upgrade to 4.0 from 3.8.9 cause NPE with maven plugin database upgrade test

### ISSUE THREAD

**Issue by jgribonvald** [liquibase/liquibase-hibernate#258]
Hello,
I've just tested to upgrade the liquibase version, but it fails on error. 
Following is the error when running `./mvnw compile liquibase:update`:

```
[ERROR]      liquibase.exception.MigrationFailedException: Migration failed for change set config/liquibase/changelog/20180326145110_main_schema.xml::1421860634824-58::xxxxxxxxxxx (manual):
[ERROR]      Reason: java.lang.NullPointerException
```

For having the whole stacktrace of the problem you can watch here the travis test: https://travis-ci.com/github/GIP-RECIA/esup-publisher/builds/175842520

On an other side, before upgrading liquibase I've this upgrade:https://travis-ci.com/github/GIP-RECIA/esup-publisher/builds/175814956 with liquibase-ext that worked well with liquibase 3.8.9.

Thanks

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-404) by [Unito](https://www.unito.io/learn-more)

**Comment by filipelautert** [comment]
Could you please try again in a more recent version of liquibase as a lot has been fixed over the years. Please reopen the issue if it still persists.
