### ISSUE TITLE
After installing it, what else do I need to do, please?

### ISSUE THREAD

**Issue by mfgabriel92** [liquibase/liquibase-hibernate#260]
I have a project with JPA only, no Spring. I have a `persistence.xml` file with the database configuration, and I created a couple of files related to Liquibase located in `resources/META-INF/database`. They are:

* `liquibase.properties`; database configuration
* `dbchangelog.xml`: as a test included one changelog for one table here with `<include />`
* `changelogs/`: the aforementioned changelog

My test files extend a base one that initializes the `EntityManager` by looking for the PU name set in `persistence.xml`. The problem now is that when I have `org.liquibase.ext:liquibase-hibernate4` version 3.6 installed, when I run a test, it will throw an exception:

> java.lang.AbstractMethodError: Receiver class org.hibernate.envers.event.spi.EnversIntegrator does not define or inherit an implementation of the resolved method 'abstract void integrate(org.hibernate.boot.Metadata, org.hibernate.engine.spi.SessionFactoryImplementor, org.hibernate.service.spi.SessionFactoryServiceRegistry)' of interface org.hibernate.integrator.spi.Integrator.

It points to the base test file, on this line

```java
entityManagerFactory = Persistence.createEntityManagerFactory("JPA-Specialist-PU");
```

The problem without this plugin is that since I'm using liquibase and using another file to set-up the database configuration, I cannot create a PU name, and without at least one PU name, I cannot instantiate `EntityManager` and perform operations on my database. But I didn't find anything else explaining what to do next after installing.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-584) by [Unito](https://www.unito.io/learn-more)

**Comment by filipelautert** [comment]
Could you please try again in a more recent version of liquibase as a lot has been fixed over the years. Please reopen the issue if it still persists.
