### ISSUE TITLE
add property for nationalized character

### ISSUE THREAD

**Issue by radianer** [liquibase/liquibase-hibernate#268]
hi,

it is possible to add the hibernate property `hibernate.use_nationalized_character_data=true` to the URL to generate NVARCHAR instandof VARCHAR? Or add a property to liquibase to do the same thing?

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-847) by [Unito](https://www.unito.io/learn-more)

**Comment by filipelautert** [comment]
Fixed by https://github.com/liquibase/liquibase-hibernate/pull/275 .
