### ISSUE TITLE
please release 4.2.1 that is compatible with liquibase-core 4.2.1

### ISSUE THREAD

**Issue by alan-czajkowski** [liquibase/liquibase-hibernate#282]
thanks

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-970) by [Unito](https://www.unito.io/learn-more)

**Comment by alan-czajkowski** [comment]
any ETA on this?

**Comment by alan-czajkowski** [comment]
@nvoxland any ETA on this?

**Comment by nvoxland** [comment]
There was a bug in 4.2.0 that kept the hibernate extension from working. 
We're working on final testing of a 4.2.1 version that will support it, and will release the hibernate extension along with it

**Comment by alan-czajkowski** [comment]
@nvoxland (im)patiently waiting :D
