### ISSUE TITLE
ClassLoadingException: Unable to load class

### ISSUE THREAD

**Issue by Euklios** [liquibase/liquibase-hibernate#288]
I have been using Flyway for a few weeks now, manually writing our migration scripts.
However, we've been facing some issues regarding the limitations of Flyway, one of them being the need to manually write our SQL-files, which lead to some (a lot of) discrepancies between our JPA-entities and the actual database.
That's why I've been trying to migrate away from Flyway towards Liquibase, with the main goal being to automatically create migrations based on our entity-changes.

My goal is something like Djangos `makemigrations` command.

My current environment looks as follows:
Java: 15
Postgresql: 13
maven: 3.6

spring-boot-starter-parent:2.4.0
spring-boot-starter-data-jpa:2.4.0
hibernate:5.4.23.Final
liquibase-core:4.2.2

The liquibase-maven-plugin is configured using maven as follows:

```xml
<plugin>
  <groupId>org.liquibase</groupId>
  <artifactId>liquibase-maven-plugin</artifactId>
  <version>${liquibase.version}</version>
  <dependencies>
    <dependency>
      <groupId>org.liquibase.ext</groupId>
      <artifactId>liquibase-hibernate5</artifactId>
      <version>4.2.2</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
      <version>${project.parent.version}</version>
    </dependency>
    <dependency>
      <groupId>javax.validation</groupId>
      <artifactId>validation-api</artifactId>
      <version>2.0.1.Final</version>
    </dependency>
  </dependencies>
  <configuration>
    <changeLogFile>${project.basedir}/src/main/resources/db/changelog/changelog-master.xml</changeLogFile>
    <diffChangeLogFile>${project.basedir}/src/main/resources/db/changelog/changes/changelog.xml</diffChangeLogFile>
    <driver>org.postgresql.Driver</driver>

    <url>jdbc:postgresql://localhost:2345/uradouga</url>
    <username>my-user</username>
    <password>my-password</password>
    <referenceUrl>hibernate:spring:com.example?dialect=org.hibernate.dialect.PostgreSQL10Dialect&amp;hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&amp;hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy&amp;hibernate.enhanced_id=true</referenceUrl>
    <referenceDriver>liquibase.ext.hibernate.database.connection.HibernateDriver</referenceDriver>
  </configuration>
</plugin>
```

My changelog-master.xml just contains an empty databaseChangeLog object, as follows:

```xml
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog">

</databaseChangeLog>
```

If I now run `mvnw liquibase:diff`, I receive the following error: `ClassNotFoundException: Could not load requested class : com.example.client.model.CapabilityModel` and the generated changelog.xml would drop the entire database.

I tried down and upgrading Liquibase, hibernate, and Liquibase-hibernate, but the error I received did not change.
I also tried to change the classpath by appending the jar-file created when running `mvnw package`, the jar.original file (as the generated jar file is using spring-boot, where the file-structure is different), and the target/classes folder itself.
I also tried to included my module itself as a dependency on the `liquibase-maven-plugin`.

An example class looks like this:

```java
@Data
@Entity
@Table(name = "capability")
public class CapabilityModel
{
  @Id
  @GeneratedValue(generator = "UUID")
  @GenericGenerator(name = "UUID", strategy = "org.hibernate.id.UUIDGenerator")
  @Column(name = "pk", updatable = false, nullable = false)
  private UUID uuid;
  
  private CapabilityType type;
  private String value;
}
```

I'd appreciate any pointers/help I can get.
I'm assuming that this is a configuration issue on my side, however, I have no clue where I went wrong.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1083) by [Unito](https://www.unito.io/learn-more)

**Comment by Euklios** [comment]
Log when running `mvnw -X liquibase:diff`
[maven.log](https://github.com/liquibase/liquibase-hibernate/files/5760280/maven.log)

**Comment by molivasdat** [comment]
Hi @Euklios Did you get a resolution to your issue? If not, I can see what our devs suggest.

**Comment by EdwardVargatuk** [comment]
Hi everyone!
I have exactly the same problem and log after running mvn -X liquibase:diff
Also have similar configuration and test classes.
use:
org.liquibase:liquibase-maven-plugin:jar:4.2.2
org.liquibase:liquibase-core:jar:4.2.2
org.liquibase.ext:liquibase-hibernate5:jar:4.2.2
Java: 15
spring-boot-starter-parent: 2.3.2.RELEASE
mysql: 8.0.19

**Comment by EdwardVargatuk** [comment]
I found the reason of failure, it was because we use --enable-preview in our plugins and use this preview features in project.
<plugin>
               <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>15</source>
                    <target>15</target>
                    <compilerArgs>--enable-preview</compilerArgs>
                </configuration>
</plugin>
so refusingl to use new priview features in the project and without "--enable-preview" liquibase plugin works fine.

**Comment by filipelautert** [comment]
Nice, thanks for the feedback! Probably some preview features from java 15 were interfering, as we test only with LTS java version.
