### ISSUE TITLE
Release 4.3.4 is missing from public repos

### ISSUE THREAD

**Issue by alan-czajkowski** [liquibase/liquibase-hibernate#323]
https://mvnrepository.com/artifact/org.liquibase.ext/liquibase-hibernate5

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1641) by [Unito](https://www.unito.io)

**Comment by filipelautert** [comment]
Sorry, that's too long ago and I can't be fixed anymore.
