### ISSUE TITLE
Hibernate Diff does not produce a "drop colum" changeset

### ISSUE THREAD

**Issue by runkelstein** [liquibase/liquibase-hibernate#357]
Hi,

I have a simple database from where I just want to delete column. So I removed the field in the java class. So I was expecting that when I would diff between my database and hibernate as reference I would get a drop column changeset generated.

But this is not happening. I just get an empty diff changeset.

But when I completely regenerate the entire changelog with hibernate the deleted column is no longer part of the full changeset.

Furthermore I tested the result what happens when I do a diff between 2 databases. Then it works and the drop column is part of the changeset, as expected.

Is this a bug, or am I missing anything here?

**Comment by filipelautert** [comment]
This has been fixed in recent version. Please reopen the issue if it still persists.
