### ISSUE TITLE
Compatibility with Hibernate 5.6.2

### ISSUE THREAD

**Issue by unlimitedsola** [liquibase/liquibase-hibernate#378]
The latest version is not compatible with Hibernate 5.6.2+ because the `org.hibernate.id.enhanced.SequenceStyleGenerator#generatorKey` method has been removed.

Ref: https://github.com/hibernate/hibernate-orm/commit/9a14200ca2028f005cd129989004bfef1e52c843

**Comment by DanielFran** [comment]
@nvoxland With liquibase-hibernate 4.6.1+ this plugin cannot be used anymore with spring-boot 2.5+ due to incompatibilities with hibernate 5.6.2+

**Comment by apeinsip** [comment]
Any new news on this issue?

**Comment by DanielFran** [comment]
@nvoxland @r2liquibase This is blocking use of liquibase 4.6.1+

**Comment by davebrown1975** [comment]
Any update on this?

**Comment by filipelautert** [comment]
Hi @DanielFran @unlimitedsola  - can you confirm if this still an issue with latest liquibase-hibernate5 version? I see that https://github.com/liquibase/liquibase-hibernate/pull/354 removed references to class org.hibernate.id.enhanced.SequenceStyleGenerator,  was merged on May 31st.

**Comment by DanielFran** [comment]
> Hi @DanielFran @unlimitedsola  - can you confirm if this still an issue with latest liquibase-hibernate5 version? I see that https://github.com/liquibase/liquibase-hibernate/pull/354 removed references to class org.hibernate.id.enhanced.SequenceStyleGenerator,  was merged on May 31st.

Hi @filipelautert, issue dies not exists anymore.

**Comment by filipelautert** [comment]
Thanks @DanielFran !
