### ISSUE TITLE
Dependency Management - liquibase-test-harness should be scoped to 'test'

### ISSUE THREAD

**Issue by nmck257** [liquibase/liquibase-hibernate#397]
If the name is to be trusted, then liquibase-test-harness is only relevant when building/running tests. But, it's declared in the pom with default / "compile" scope.

This causes bloat to client builds (unless they explicitly override the scope themselves) especially since liquibase-test-harness brings in Groovy as a dependency, which isn't relevant to many client apps.

**Comment by filipelautert** [comment]
Fixed somewhere down the road as it is on parent-pom with correct scope.
