### ISSUE TITLE
Compatibility with Hibernate 6

### ISSUE THREAD

**Issue by odesenfans** [liquibase/liquibase-hibernate#406]
Hello, are there plans to support Hibernate 6?

**Comment by aleksey-stukalov** [comment]
@odesenfans you can use JPA Buddy https://www.jpa-buddy.com/:) It already supports most of  Hibernate 6!

**Comment by nvoxland** [comment]
I'm looking into @papegaaij 's PR for this

**Comment by filipelautert** [comment]
Support has been released with Liquibase 4.18.

**Comment by thetric** [comment]
@filipelautert No, it does not seem so: https://github.com/liquibase/liquibase-hibernate/compare/v4.17.2...v4.18.0
The release notes are misleading. It was merged after the 4.18.0 release of liquibase-hibernate: https://github.com/liquibase/liquibase-hibernate/compare/v4.18.0...main
