### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [liquibase/liquibase-hibernate#474]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by codespearhead** [comment]
Perhaps they don't know about this GitHub feature (I didn't), but I encourage you to [submit the vulnerability report according to their guidelines](https://github.com/liquibase/liquibase/security/policy#how-to-submit-a-vulnerability) until an official answer is issued.

**Comment by filipelautert** [comment]
Hello @igibek ! Security reports have been enabled somewhere in the last year. Please submit it using the appropriated github channel if the issue still persists, thanks!
