### ISSUE TITLE
diff changelog is removing unique constraint since 4.21.0 (hibernate6 + postgresql)

### ISSUE THREAD

**Issue by amazing4u** [liquibase/liquibase-hibernate#479]
Hi,

with version 4.21.0 and 4.21.1 of **liquibase-hibernate6** there is a new bug.
The diff changeLog creates a change which is removing the unique constraint.

Here is a sample to reproduce:

Entity:
```
@Entity
@Builder
@AllArgsConstructor(access = AccessLevel.PACKAGE)
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Getter
@Setter
@Table(name = "users")
public class UserEntity implements UserDetails {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Setter(AccessLevel.NONE)
    @Column(name = "id")
    private long id;

    @Column(name = "username", unique = true, nullable = false)
    private String username;

    @Column(name = "password", nullable = false)
    private String password;
    }
}
```

1. mvn:liquibase:generateChangeLog is working fine and creates following sql:
```
-- changeset Neo:1681571634046-1
CREATE TABLE "users" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "password" VARCHAR(255) NOT NULL, "username" VARCHAR(255) NOT NULL, CONSTRAINT "users_pkey" PRIMARY KEY ("id"));

-- changeset Neo:1681571634046-2
ALTER TABLE "users" ADD CONSTRAINT "uc_usersusername_col" UNIQUE ("username");

```

2. mvn liquibase:update to apply the change and create the table

3. mvn liquibase:diff to create a diff. Expecting no changes. But it creates following change:
```
-- changeset Neo:1681630676734-2
ALTER TABLE users DROP CONSTRAINT uc_usersusername_col;

```

I am using liquibase-maven-plugin version 4.21.1 + liquibase-hibernate6 version 4.21.1 + postgresql 15.2

application.properties
```
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
```

pom.xml:
```
<referenceDriver>liquibase.ext.hibernate.database.connection.HibernateDriver</referenceDriver>
<referenceUrl>
       hibernate:spring:net.myclient.myclient.model?dialect=org.hibernate.dialect.PostgreSQLDialect
</referenceUrl>

**Comment by EggOxygen** [comment]
Same here. It looks like it won't handle any DDL operations related to unique constraint now.

**Comment by fleboulch** [comment]
It is linked to #436

**Comment by filipelautert** [comment]
So @fleboulch - https://github.com/liquibase/liquibase-hibernate/issues/436 says that it dropped and recreated the constraints. So now it is just dropping... 
@amazing4u thanks for the example code, let's see if we can create some tests around it to fix this.

**Comment by filipelautert** [comment]
Hello @amazing4u @javaboy79  - would you be able to test using the jars from https://github.com/liquibase/liquibase-hibernate/actions/runs/4756616505?pr=480 ?

**Comment by wslaghekke** [comment]
@filipelautert I had issues with constraints being dropped on 4.21.0 as well, a few of the drop issues are gone with the new jar, but it is still dropping a few.
The dropped constraints are always in tables that have more than 1 constraint, could that be caused by them having the same name? (because you use the table name as the name of the index)

```
    protected Index getBackingIndex(UniqueConstraint uniqueConstraint, org.hibernate.mapping.Table hibernateTable, DatabaseSnapshot snapshot) {
        Index index = new Index();
        index.setRelation(uniqueConstraint.getRelation());
        index.setColumns(uniqueConstraint.getColumns());
        index.setUnique(true);
        index.setName(hibernateTable.getName() + "_IX");    <-- here

        return index;
    }
```

https://github.com/liquibase/liquibase-hibernate/pull/480/files#diff-60252904a8a1921f432e9a194d85c9eed4ffbe3a15ef94660e2c2a27e6c6cd3aR119

**Comment by filipelautert** [comment]
Nice catch @wslaghekke ! As I don't have it setup yet, I created a simple fix and built it: https://github.com/liquibase/liquibase-hibernate/actions/runs/4756901871?pr=480 . Could you help to test again? If it works I'll think of a more elegant solution then just adding 4 random chars to the idx name.

**Comment by wslaghekke** [comment]
@filipelautert I've just tested that version and my changelog is empty now so that has fixed the issue.

**Comment by wslaghekke** [comment]
@filipelautert Any idea when the fixed version will be released?

**Comment by filipelautert** [comment]
Hello @wslaghekke -maybe this or next week.
