### ISSUE TITLE
data type modification not tracked

### ISSUE THREAD

**Issue by bmoers** [liquibase/liquibase-hibernate#48]
Changing an enum type to string is not tracked in change sets.

E.g. changing chartType from (default) int ....

```
@Entity
public class Chart {
    public enum ChartType {
            AREA, AREASPLINE, BAR, COLUMN, LINE, PIE, SCATTER, SPLINE
    }

    @Column(nullable = false, length = 50)
    private ChartType chartType;
}
```

to string

```
@Entity
public class Chart {
    public enum ChartType {
            AREA, AREASPLINE, BAR, COLUMN, LINE, PIE, SCATTER, SPLINE
    }

    @Column(nullable = false, length = 50)
    @Enumerated(EnumType.STRING)
    private ChartType chartType;
}
```

"change set" should be

```
<modifyDataType
tableName="chart" columnName="chart_type" newDataType="VARCHAR(50)" />
```

but is empty

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-483) by [Unito](https://www.unito.io/learn-more)

**Comment by nvoxland** [comment]
The reason these tend to be ignored is because how hibernate represents the datatype is usually different than how the database represents the datatype even when they are actually the same. I'm looking at ways to improve this with Liquibase 4.

**Comment by hImAnShUdHaWaN** [comment]
Do we any inputs on it yet.. I am facing issues when adding @lob to to my string type.

**Comment by strongant** [comment]
@bmoers  How do you resolve it ?

**Comment by bmoers** [comment]
Phew! Long time ago.
As far I can remember I couldn't resolve it and decided to replace the enum with a custom entity.

**Comment by RicoApfelbeck** [comment]
we have got the same @lob issue, how can I help to fix it?

**Comment by zak905** [comment]
any updates about this ? facing the same issue.

**Comment by MrKuip** [comment]
Is this problem solved already?

**Comment by AndreiSasu** [comment]
I get the same issue, trying to change a string property from the default varchar(255) to varchar(2048)
`@Column(columnDefinition="VARCHAR(2048)")`

what I ended up doing was editing the changelog files manually and issuing
`mvn liquibase:clearCheckSums` but this could not be an option in production

**Comment by tbieniek** [comment]
Any progress with this issue ?

**Comment by fortu42** [comment]
> I get the same issue, trying to change a string property from the default varchar(255) to varchar(2048) `@Column(columnDefinition="VARCHAR(2048)")`

I have the same exact problem.
I tried a patched version, without class `liquibase.ext.hibernate.diff.ChangedColumnChangeGenerator` and I can confirm that the column change is detected.
I'm going to try this patched version with other cases to see if we have good results. This issue started in 2014, we are in 2022, in the meantime hibernate changed (a lot, I think), so things could be different now.

**Comment by kataggart** [comment]
mentioned in discord today https://discord.com/channels/700506481111597066/967060802068697099/996772895101554709

**Comment by maximebochon** [comment]
Same issue trying to change an `OffsetDateTime` / `@Column(columnDefinition="TIMESTAMP WITH TIME ZONE")` to a `LocalDate` / `@Column(columnDefinition="DATE")` using Liquibase with Hibernate and Postgres on a Java/Spring project.
