### ISSUE TITLE
Maven Generate Diff From Entity  : Error The application must supply JDBC connections

### ISSUE THREAD

**Issue by tlarue** [liquibase/liquibase-hibernate#482]
Hello,

I want to generate diff changelog between hibernate mapping entity versus a integration database using plugin maven.
My configuration is : 
Springboot 3.0.5
Hibernate 6.1.8
Liquibase and plugin maven  4.21.1

When I try to call command diff by plugin, I obtain following error : 

![image](https://user-images.githubusercontent.com/25803130/233972151-76961515-22dd-434a-9ae3-a4416d299225.png)

I debugged liquibase code, and I see that good implementation is finded (HibernateSpringPackage....)

![image](https://user-images.githubusercontent.com/25803130/233972497-aaa3046a-989f-41e4-a6e3-8219b1839ecb.png)

But when it try to set Connection , it failed (normal.. :( )

![image](https://user-images.githubusercontent.com/25803130/233972593-349c368d-c7b0-4abd-a73e-60cde3ebc6bb.png)

![image](https://user-images.githubusercontent.com/25803130/233972885-8a4574d5-ea56-4e73-802e-0c236f0ba07f.png)

Here my plugin configuration in my pom.xml

![image](https://user-images.githubusercontent.com/25803130/233973238-df38c446-40ef-4935-9e1a-247007d467a0.png)

I don't see my error :/ , can you help me please.

Next, in the log, for information I have other errors, maybe a edge effect of the first error

![image](https://user-images.githubusercontent.com/25803130/233973872-e9b4f50a-6478-448b-9896-d53d5b28341b.png)

Thank you for your help

**Comment by filipelautert** [comment]
Fixed by https://github.com/liquibase/liquibase-hibernate/pull/616 on 4.26.0
