### ISSUE TITLE
is 4.23.0+ not going to support Hibernate 5?

### ISSUE THREAD

**Issue by alan-czajkowski** [liquibase/liquibase-hibernate#506]
https://repo1.maven.org/maven2/org/liquibase/ext/liquibase-hibernate5/

**Comment by hetzijzo** [comment]
What is the current status? The 4.23.0 is a minor upgrade from 4.22.0 and just dropped the hibernate-5 support? Is this a mistake or done on purpose?

**Comment by filipelautert** [comment]
Hey @alan-czajkowski - 4.24.0 has been released bringing back hibernate5 packages : https://mvnrepository.com/artifact/org.liquibase.ext/liquibase-hibernate5/4.24.0
