### ISSUE TITLE
Liquibase liquibase-maven-plugin creates tables but tables cannot be found in Integration Tests: org.hibernate.HibernateException

### ISSUE THREAD

**Issue by rajivj2** [liquibase/liquibase-hibernate#66]
Hi

I am using Liquibase. I want the database tables to be created before the Integration Tests.

The code is located on GitHib: https://github.com/rajivj2/example2/

The EmployeeJpaDAOIT.java is the class that contains the test. All I want to do is have the tables created before the test actually starts. I can see the plugin creates the tables at runtime but the Integration Tests throws the following Exception:

Caused by: org.hibernate.HibernateException: Missing table: employee

I have tried various things but the table cannot be found. Could you please look into what the issue is?

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-484) by [Unito](https://www.unito.io/learn-more)

**Comment by nvoxland** [comment]
This issue had gotten pushed to the bottom of the stack, unfortuantely. Were you able to figure out the problem? Your repository isn't compiling for me, currently.
