### ISSUE TITLE
hibernate4.2-3.3 and hibernate4.2-3.4 'mvn package'

### ISSUE THREAD

**Issue by flybyray** [liquibase/liquibase-hibernate#70]
I cannot build packages for releases! I am using 'mvn clean' and 'mvn package' to do so.
For the liquibase (parent .. core ..) sources this command works.

> -------------------------------------------------------
>  T E S T S
> -------------------------------------------------------
> Running liquibase.ext.hibernate.snapshot.TableSnapshotGeneratorTest
> Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.436 sec
> Running liquibase.ext.hibernate.HibernateIntegrationTest
> Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 1.468 sec <<< FAILURE!
> Running liquibase.ext.hibernate.database.connection.HibernateConnectionTest
> Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
> Running liquibase.ext.hibernate.database.HibernateSpringDatabaseTest
> Tests run: 4, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.519 sec <<< FAILURE!
> Running liquibase.ext.hibernate.database.HibernateClassicDatabaseTest
> 
> Results :
> 
> Tests in error: 
>   runGeneratedChangeLog(liquibase.ext.hibernate.HibernateIntegrationTest)
>   hibernateSchemaExport(liquibase.ext.hibernate.HibernateIntegrationTest)
>   hibernateSchemaUpdate(liquibase.ext.hibernate.HibernateIntegrationTest)
>   simpleSpringScanningUrl(liquibase.ext.hibernate.database.HibernateSpringDatabaseTest)
>   simpleSpringUrl(liquibase.ext.hibernate.database.HibernateSpringDatabaseTest)
>   simpleHibernateUrl(liquibase.ext.hibernate.database.HibernateClassicDatabaseTest)
>   hibernateUrlWithNamingStrategy(liquibase.ext.hibernate.database.HibernateClassicDatabaseTest)
> 
> Tests run: 12, Failures: 0, Errors: 5, Skipped: 0
> 
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 3:06.560s
> [INFO] Finished at: Tue Dec 02 12:17:37 CET 2014
> [INFO] Final Memory: 21M/103M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project liquibase-hibernate4.2: There are test failures.
> [ERROR] 
> [ERROR] Please refer to /home/synapplix/git/play-modules/liquibase/lib-ext/liquibase-hibernate/target/surefire-reports for the individual test results.
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

What are the requirements not met? I try to test and prepare some pull requests but it is not possible to test on release versions? Are there some additional wiki hints?

**Comment by nvoxland** [comment]
The tests are all passing for 3.5
