### ISSUE TITLE
liquibase-diff changeset generation broken since 4.28 when comparing to a Spring Hibernate Database

### ISSUE THREAD

**Issue by Guschtel** [liquibase/liquibase-hibernate#716]
### Search first

Copying parts of the issue description from https://github.com/liquibase/liquibase/issues/6148#issue-2438921543 because I think that the issue is purely related to liquibase-hibernate and I think that there is an easy fix for the problem.

### Description
Since liquibase 4.28 it seems like that changes are still detected but don't make it to the changeset when using the liquibase diff-changelog command.

### Steps To Reproduce
Create a JPA Entity with a change compared to your database and configure liquibase-hibernate to create diffs.
Run the liquibase `diff-changelog` command.

### Expected/Desired Behavior
Liquibase-Hibernate 4.28 and onwards should create a changelog file like 4.27 did.

### Liquibase-Hibernate Version
4.28, 4.29

Database Vendor & Version
Oracle or H2 comparing to a Spring Hibernate JPA Entities configuration

### Liquibase Integration
Gradle

### Liquibase Extensions
liquibase-hibernate6

### OS and/or Infrastructure Type/Provider
Windows

### Are you willing to submit a PR?
- [x] I'm willing to submit a PR (Thank you!)

**Comment by Sruthi-Ganesh** [comment]
Any workaround on this issue with 4.28.0?
Our team is currently blocked as we also cannot downgrade to 4.27.0 or prior due to the bug https://github.com/liquibase/liquibase-hibernate/issues/500 which is fixed only in https://github.com/liquibase/liquibase-hibernate/releases/tag/v4.28.0 (https://github.com/liquibase/liquibase-hibernate/pull/679)

**Comment by Guschtel** [comment]
> Any workaround on this issue with 4.28.0?
> Our team is currently blocked as we also cannot downgrade to 4.27.0 or prior due to the bug https://github.com/liquibase/liquibase-hibernate/issues/500 which is fixed only in https://github.com/liquibase/liquibase-hibernate/releases/tag/v4.28.0 (https://github.com/liquibase/liquibase-hibernate/pull/679)

You can implement an own extension and provide this. Or use a patched library, that's what we do currently. It both results in the same, that you need to provide an additional library.
