### ISSUE TITLE
@UniqueConstraint is giving null pointer exception

### ISSUE THREAD

**Issue by svennela** [liquibase/liquibase-hibernate#73]
Hi,

I am using Oauth based 2.0 version.I am running mvn pulgin to generate database log for jpa. I am getting null pointer exception when i run below command.  

mvn compile liquibase:diff

@Table(name = "T_USERRELEATION",uniqueConstraints = @UniqueConstraint(columnNames = { "FROM_USER_ID", "TO_USER_ID" }))

 
@JoinColumn(name = "FROM_USER_ID", nullable = false)
    @NotNull
    private User fromUser; // (userId)
    
    
 	@JoinColumn(name = "TO_USER_ID", nullable = false)
	@NotNull
 	private User toUser; // (userId)

**Comment by sdoxsee** [comment]
Same here

**Comment by wbsljh** [comment]
same here

**Comment by nvoxland** [comment]
I'm not able to replicate this in the code for liquibase 3.5.1 + hibernate 3.6. They should be out in the next  week or so
