### ISSUE TITLE
Release liquibase-hibernate3 with support for liquibase-core 3.3.x

### ISSUE THREAD

**Issue by mahileeb** [liquibase/liquibase-hibernate#80]
Current version of hibernate3 branch is not compatible with liquibase-core 3.3.x. TableSnapshotGenerator refers to old version of PrimaryKey.addColumn

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-485) by [Unito](https://www.unito.io/learn-more)

**Comment by alexey-semenov** [comment]
Hi guys! Could someone take a look? https://github.com/liquibase/liquibase-hibernate/pull/269

**Comment by alexey-semenov** [comment]
Could be closed I guess. The fix was merged https://github.com/liquibase/liquibase-hibernate/pull/269
