### ISSUE TITLE
How to rename a table when this table is used in my initial_chanset.xml.

### ISSUE THREAD

**Issue by manodupont** [liquibase/liquibase-hibernate#84]
Lets say i have a baseline.xml and changeset1.xml.

In baseline.xml, it creates a view using sql statement pointing to a table names "TABLE1".
In changeset1.xml, i rename "TABLE1" to "TABLE_TEST".

So it gives me an error telling me that TABLE1 doesn't exist anymore (pointing to my baseline.xml).

How Am I supposed to be able to do that !%

Thank you.

**Comment by nvoxland** [comment]
This should be fixed in Liquibase 3.5.x which will be supported in liquibase-hibernate 3.6 coming out next week.
