### ISSUE TITLE
diffChangeLog will not generate indexes from hbm files

### ISSUE THREAD

**Issue by nvoxland** [liquibase/liquibase-hibernate#85]
Moved from https://liquibase.jira.com/browse/CORE-2294

We're using hbm files to build a database, and they include indexes:
eg:

    <hibernate-mapping>
    <class name="some.package.SomeClass" table="SomeTable">
    <id name="id" type="java.lang.String">
    <column name="id" length="64" />
    <generator class="assigned">
    <param name="identifier_normalizer">org.hibernate.cfg.Configuration$ObjectNameNormalizerImpl@66e74f94             
    </param>
    </generator>
    </id>
    <property name="accountId" type="java.lang.String">
    <column name="accountId" length="64" index="IDX_ACCOUNTID_COL"/>
    </property>
    </class>
    </hibernate-mapping>

We ran into the exception reported in issueCORE-2206. The workaround from Nikolay worked, so the exception was eliminated, but indexes still were not created. They were not being added to the change log.
I tracked the problem down to MissingIndexChangeGenerator.java, line 27. Indexes are filtered out if the reference database is a HibernateDatabase, in our case, a set of .hbm.xml files.
Removing "referenceDatabase instanceof HibernateDatabase" from that line resolved the issue, and Liquibase generated index change logs from a .hbm.xml file correctly.

**Comment by emailtowaqas** [comment]
Any idea when would fix be released? Thanks.

**Comment by EricPeladan** [comment]
Je suis absent(e) du bureau jusqu'au 31/08/2015

Je répondrai à votre message dès mon retour.


Remarque : ceci est une réponse automatique à votre message  "Re:
[liquibase-hibernate] diffChangeLog will not generate indexes from hbm
files (#85)" envoyé le 17/08/2015 20:04:17.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.
--   
Accédez aux meilleurs tarifs Air France, gérez vos réservations et enregistrez-vous en ligne sur  http://www.airfrance.com  
Find best Air France fares, manage your reservations and check in online at  http://www.airfrance.com  Les données et renseignements contenus dans ce message peuvent être de nature confidentielle et soumis au secret professionnel et sont destinés à l'usage exclusif du destinataire dont les coordonnées figurent ci-dessus. Si vous recevez cette communication par erreur, nous vous demandons de ne pas la copier, l'utiliser ou la divulguer. Nous vous prions de notifier cette erreur à l'expéditeur et d'effacer immédiatement cette communication de votre système. Société Air France - Société anonyme au capital de 126 748 775 euros - RCS Bobigny (France) 420 495 178 - 45, rue de Paris, Tremblay-en-France, 95747 Roissy Charles de Gaulle CEDEX  
The data and information contained in this message may be confidential and subject to professional secrecy and are intended for the exclusive use of the recipient at the address shown above. If you receive this message by mistake, we ask you not to copy, use or disclose it. Please notify this error to the sender immediately and delete this message from your system. Société Air France - Limited company with capital of 126,748,775 euros - Bobigny register of companies (France) 420 495 178 - 45, rue de Paris, Tremblay-en-France, 95747 Roissy Charles de Gaulle CEDEX  Pensez à l'environnement avant d'imprimer ce message.  
Think of the environment before printing this mail.

**Comment by robertoschwald** [comment]
See also #100

**Comment by nvoxland** [comment]
This should be fixed by #100
