### ISSUE TITLE
How can pass custom hibernate properties when scaning packages?

### ISSUE THREAD

**Issue by zhanhb** [liquibase/liquibase-hibernate#87]
I read the souce code of class HibernateSpringDatabase carefully for hours, but I can't find any solution. The properties in url connection string takes no effect.
By the way, I am using package scan rather than xml file.

**Comment by nvoxland** [comment]
With liquibase-hibernate 3.6, you can now pass hibernate parameters to your hibernate database url, like ?hibernate.dialect=com.example.Dialect
