### ISSUE TITLE
NullPointerException when execute 'mvn liquibase:diff'

### ISSUE THREAD

**Issue by cgagne** [liquibase/liquibase-hibernate#88]
We have a null pointer exception when we run the mvn command line liquibase:diff on a @manyToMany relationship defined below please see: 
http://stackoverflow.com/questions/31808537/nullpointerexception-when-execute-mvn-liquibasediff

The proposed work arround is to downgrade liquibase version to 3.3.1 (from 3.3.2).

From my undestanding it was supposed to be fix in 3.3.2 see jhipster's related issue:
https://github.com/jhipster/generator-jhipster/issues/754

which is tied to an older liquibase's issue:
https://github.com/liquibase/liquibase-hibernate/issues/76

Thanks

================================
POM.XML working solution:
    liquibase-hibernate4.version: 3.5
    liquibase-slf4j.version: 1.2.1
    liquibase.version: 3.3.1

jhipster: v 1.4.7
MAC OSX: Yosemite 10.10.4
Apache Maven 3.3.3
Java version: 1.8.0_45, vendor: Oracle Corporation

**Comment by EricPeladan** [comment]
Je suis absent(e) du bureau jusqu'au 31/08/2015

Je répondrai à votre message dès mon retour.


Remarque : ceci est une réponse automatique à votre message
"[liquibase-hibernate] NullPointerException when execute 'mvn
liquibase:diff' (#88)" envoyé le 08/08/2015 17:03:06.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.
--   
Accédez aux meilleurs tarifs Air France, gérez vos réservations et enregistrez-vous en ligne sur  http://www.airfrance.com  
Find best Air France fares, manage your reservations and check in online at  http://www.airfrance.com  Les données et renseignements contenus dans ce message peuvent être de nature confidentielle et soumis au secret professionnel et sont destinés à l'usage exclusif du destinataire dont les coordonnées figurent ci-dessus. Si vous recevez cette communication par erreur, nous vous demandons de ne pas la copier, l'utiliser ou la divulguer. Nous vous prions de notifier cette erreur à l'expéditeur et d'effacer immédiatement cette communication de votre système. Société Air France - Société anonyme au capital de 126 748 775 euros - RCS Bobigny (France) 420 495 178 - 45, rue de Paris, Tremblay-en-France, 95747 Roissy Charles de Gaulle CEDEX  
The data and information contained in this message may be confidential and subject to professional secrecy and are intended for the exclusive use of the recipient at the address shown above. If you receive this message by mistake, we ask you not to copy, use or disclose it. Please notify this error to the sender immediately and delete this message from your system. Société Air France - Limited company with capital of 126,748,775 euros - Bobigny register of companies (France) 420 495 178 - 45, rue de Paris, Tremblay-en-France, 95747 Roissy Charles de Gaulle CEDEX  Pensez à l'environnement avant d'imprimer ce message.  
Think of the environment before printing this mail.

**Comment by nvoxland** [comment]
This should be fixed with Liquibase 3.5.2 + Liquibase-Hibernate 3.6 released next week
