### ISSUE TITLE
liquibase-hiberante5

### ISSUE THREAD

**Issue by zhanhb** [liquibase/liquibase-hibernate#89]
when will this release published?

**Comment by EricPeladan** [comment]
Je suis absent(e) du bureau jusqu'au 31/08/2015

Je répondrai à votre message dès mon retour.


Remarque : ceci est une réponse automatique à votre message
"[liquibase-hibernate] liquibase-hiberante5 (#89)" envoyé le 10/08/2015
10:44:34.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.
--   
Accédez aux meilleurs tarifs Air France, gérez vos réservations et enregistrez-vous en ligne sur  http://www.airfrance.com  
Find best Air France fares, manage your reservations and check in online at  http://www.airfrance.com  Les données et renseignements contenus dans ce message peuvent être de nature confidentielle et soumis au secret professionnel et sont destinés à l'usage exclusif du destinataire dont les coordonnées figurent ci-dessus. Si vous recevez cette communication par erreur, nous vous demandons de ne pas la copier, l'utiliser ou la divulguer. Nous vous prions de notifier cette erreur à l'expéditeur et d'effacer immédiatement cette communication de votre système. Société Air France - Société anonyme au capital de 126 748 775 euros - RCS Bobigny (France) 420 495 178 - 45, rue de Paris, Tremblay-en-France, 95747 Roissy Charles de Gaulle CEDEX  
The data and information contained in this message may be confidential and subject to professional secrecy and are intended for the exclusive use of the recipient at the address shown above. If you receive this message by mistake, we ask you not to copy, use or disclose it. Please notify this error to the sender immediately and delete this message from your system. Société Air France - Limited company with capital of 126,748,775 euros - Bobigny register of companies (France) 420 495 178 - 45, rue de Paris, Tremblay-en-France, 95747 Roissy Charles de Gaulle CEDEX  Pensez à l'environnement avant d'imprimer ce message.  
Think of the environment before printing this mail.

**Comment by IvanRF** [comment]
The current Liquibase Hibernate Extension (`liquibase-hibernate4`) **is not compatible** with Hibernate ORM 5.0.1.

Here is the error report: [AbstractMethodError in SessionFactoryImpl](https://hibernate.atlassian.net/browse/HHH-10100)

Steve Ebersole said:
> That line is attempting to call Integrators. I would assume you have Integrators not intended for use with Hibernate 5.0. That contract did change in 5.0 as discussed in the migration guide.

Also mentioned in [Liquibase + Hibernate ORM 5.0](http://stackoverflow.com/questions/32231741/liquibase-hibernate-orm-5-0/)
