### ISSUE TITLE
Liquibase:diff for defaultValue

### ISSUE THREAD

**Issue by roaned** [liquibase/liquibase-hibernate#90]
Hi,

Is it possible, after having created an entity, to add a default value in the JPA entity, then run liquibase:diff which would then alter the mysql table.
I have tried : 

```
@Column(name = "nome", nullable = false)
    private String nome = "tizio";
```
another try:
```
 @Column(name = "nome", nullable = false, columnDefinition = "default tizio")
    private String nome;
```

But liquibase:diff doesn't detect any modification in my entity compared with the database table.

**Comment by EricPeladan** [comment]
Je suis absent(e) du bureau jusqu'au 31/08/2015

Je répondrai à votre message dès mon retour.


Remarque : ceci est une réponse automatique à votre message
"[liquibase-hibernate] Liquibase:diff for defaultValue (#90)" envoyé le
15/08/2015 12:36:55.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.
--   
Accédez aux meilleurs tarifs Air France, gérez vos réservations et enregistrez-vous en ligne sur  http://www.airfrance.com  
Find best Air France fares, manage your reservations and check in online at  http://www.airfrance.com  Les données et renseignements contenus dans ce message peuvent être de nature confidentielle et soumis au secret professionnel et sont destinés à l'usage exclusif du destinataire dont les coordonnées figurent ci-dessus. Si vous recevez cette communication par erreur, nous vous demandons de ne pas la copier, l'utiliser ou la divulguer. Nous vous prions de notifier cette erreur à l'expéditeur et d'effacer immédiatement cette communication de votre système. Société Air France - Société anonyme au capital de 126 748 775 euros - RCS Bobigny (France) 420 495 178 - 45, rue de Paris, Tremblay-en-France, 95747 Roissy Charles de Gaulle CEDEX  
The data and information contained in this message may be confidential and subject to professional secrecy and are intended for the exclusive use of the recipient at the address shown above. If you receive this message by mistake, we ask you not to copy, use or disclose it. Please notify this error to the sender immediately and delete this message from your system. Société Air France - Limited company with capital of 126,748,775 euros - Bobigny register of companies (France) 420 495 178 - 45, rue de Paris, Tremblay-en-France, 95747 Roissy Charles de Gaulle CEDEX  Pensez à l'environnement avant d'imprimer ce message.  
Think of the environment before printing this mail.

**Comment by prostobog** [comment]
I used to face the same issue, even with value set like
`@Column(name = "nome", nullable = false, columnDefinition = "default tizio")
  private String nome = "tizio";`

**Comment by nvoxland** [comment]
Fixed for 3.6. You do need the data type in the columnDefintion, like columnDefinition="varchar(100) default tizio"
