### ISSUE TITLE
@Lob ignored

### ISSUE THREAD

**Issue by cesnek** [liquibase/liquibase-hibernate#91]
Hello,
I am usign liquibase-hibernate4 3.5 and MsSql.

"Lob" annotations is ignored and liquibase generate "varchar" in xml changelog and "varchar(1)" in Mssql database.

Sample:
@javax.persistence.Column
@javax.persistence.Lob
private String longText;

**Comment by EricPeladan** [comment]
Je suis absent(e) du bureau jusqu'au 31/08/2015

Je répondrai à votre message dès mon retour.


Remarque : ceci est une réponse automatique à votre message
"[liquibase-hibernate] @Lob ignored (#91)" envoyé le 19/08/2015 18:26:39.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.
--   
Accédez aux meilleurs tarifs Air France, gérez vos réservations et enregistrez-vous en ligne sur  http://www.airfrance.com  
Find best Air France fares, manage your reservations and check in online at  http://www.airfrance.com  Les données et renseignements contenus dans ce message peuvent être de nature confidentielle et soumis au secret professionnel et sont destinés à l'usage exclusif du destinataire dont les coordonnées figurent ci-dessus. Si vous recevez cette communication par erreur, nous vous demandons de ne pas la copier, l'utiliser ou la divulguer. Nous vous prions de notifier cette erreur à l'expéditeur et d'effacer immédiatement cette communication de votre système. Société Air France - Société anonyme au capital de 126 748 775 euros - RCS Bobigny (France) 420 495 178 - 45, rue de Paris, Tremblay-en-France, 95747 Roissy Charles de Gaulle CEDEX  
The data and information contained in this message may be confidential and subject to professional secrecy and are intended for the exclusive use of the recipient at the address shown above. If you receive this message by mistake, we ask you not to copy, use or disclose it. Please notify this error to the sender immediately and delete this message from your system. Société Air France - Limited company with capital of 126,748,775 euros - Bobigny register of companies (France) 420 495 178 - 45, rue de Paris, Tremblay-en-France, 95747 Roissy Charles de Gaulle CEDEX  Pensez à l'environnement avant d'imprimer ce message.  
Think of the environment before printing this mail.

**Comment by nvoxland** [comment]
Working for me with the upcoming liquibase-hibernate 3.6 + liquibase 3.5.2 release

**Comment by goostleek** [comment]
I'm still experiencing the issue on MSSQL using `liquibase-maven-plugin` with the following configuration:

```
              <plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <version>3.5.3</version>
                    <configuration>
                        <promptOnNonLocalDatabase>false</promptOnNonLocalDatabase>
                        <propertyFile>src/main/resources/liquibase/liquibase.properties</propertyFile>
                    </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.liquibase.ext</groupId>
                        <artifactId>liquibase-hibernate4</artifactId>
                        <version>3.6</version>
                    </dependency>
                    <dependency>
                        <groupId>org.springframework</groupId>
                        <artifactId>spring-beans</artifactId>
                        <version>4.3.7.RELEASE</version>
                    </dependency>
                    <dependency>
                        <groupId>org.springframework</groupId>
                        <artifactId>spring-orm</artifactId>
                        <version>4.3.7.RELEASE</version>
                    </dependency>
                    <dependency>
                        <groupId>org.springframework</groupId>
                        <artifactId>spring-context</artifactId>
                        <version>4.3.7.RELEASE</version>
                    </dependency>
                </dependencies>
            </plugin> 
```

I have an entity with `String` field annotated with `@javax.persistence.Lob` and and it still generates:

```
<column name="message_content" type="varchar(1)"/>
```
