### ISSUE TITLE
Diff with MsSql always regenerate PK 

### ISSUE THREAD

**Issue by cesnek** [liquibase/liquibase-hibernate#92]
Hello,
I am usign liquibase-hibernate4 3.5 and MsSql.

Diff with Mssql always regenerate all PK with same values.

Sample:
\<changeSet author="pubal (generated)" id="1439998529929-25">
\<dropPrimaryKey tableName="usn_vyrok"/>
\<addPrimaryKey columnNames="id_vyrok" constraintName="usn_vyrokPK" tableName="usn_vyrok"/>
\</changeSet>

**Diff message is: "clustered changed from null to true"**
But this is very platform dependent flag, and never get to changelog file.

**General solution is ignore all unknown flags in diff.**

**Comment by cesnek** [comment]
Well maybe this is more liquibase-core issue than hibernate extension.

**Comment by EricPeladan** [comment]
Je suis absent(e) du bureau jusqu'au 31/08/2015

Je répondrai à votre message dès mon retour.


Remarque : ceci est une réponse automatique à votre message
"[liquibase-hibernate] Diff with MsSql always regenerate PK  (#92)" envoyé
le 19/08/2015 18:41:16.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.
--   
Accédez aux meilleurs tarifs Air France, gérez vos réservations et enregistrez-vous en ligne sur  http://www.airfrance.com  
Find best Air France fares, manage your reservations and check in online at  http://www.airfrance.com  Les données et renseignements contenus dans ce message peuvent être de nature confidentielle et soumis au secret professionnel et sont destinés à l'usage exclusif du destinataire dont les coordonnées figurent ci-dessus. Si vous recevez cette communication par erreur, nous vous demandons de ne pas la copier, l'utiliser ou la divulguer. Nous vous prions de notifier cette erreur à l'expéditeur et d'effacer immédiatement cette communication de votre système. Société Air France - Société anonyme au capital de 126 748 775 euros - RCS Bobigny (France) 420 495 178 - 45, rue de Paris, Tremblay-en-France, 95747 Roissy Charles de Gaulle CEDEX  
The data and information contained in this message may be confidential and subject to professional secrecy and are intended for the exclusive use of the recipient at the address shown above. If you receive this message by mistake, we ask you not to copy, use or disclose it. Please notify this error to the sender immediately and delete this message from your system. Société Air France - Limited company with capital of 126,748,775 euros - Bobigny register of companies (France) 420 495 178 - 45, rue de Paris, Tremblay-en-France, 95747 Roissy Charles de Gaulle CEDEX  Pensez à l'environnement avant d'imprimer ce message.  
Think of the environment before printing this mail.

**Comment by EricPeladan** [comment]
Je suis absent(e) du bureau jusqu'au 31/08/2015

Je répondrai à votre message dès mon retour.


Remarque : ceci est une réponse automatique à votre message  "Re:
[liquibase-hibernate] Diff with MsSql always regenerate PK  (#92)" envoyé
le 19/08/2015 18:44:16.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.
--   
Accédez aux meilleurs tarifs Air France, gérez vos réservations et enregistrez-vous en ligne sur  http://www.airfrance.com  
Find best Air France fares, manage your reservations and check in online at  http://www.airfrance.com  Les données et renseignements contenus dans ce message peuvent être de nature confidentielle et soumis au secret professionnel et sont destinés à l'usage exclusif du destinataire dont les coordonnées figurent ci-dessus. Si vous recevez cette communication par erreur, nous vous demandons de ne pas la copier, l'utiliser ou la divulguer. Nous vous prions de notifier cette erreur à l'expéditeur et d'effacer immédiatement cette communication de votre système. Société Air France - Société anonyme au capital de 126 748 775 euros - RCS Bobigny (France) 420 495 178 - 45, rue de Paris, Tremblay-en-France, 95747 Roissy Charles de Gaulle CEDEX  
The data and information contained in this message may be confidential and subject to professional secrecy and are intended for the exclusive use of the recipient at the address shown above. If you receive this message by mistake, we ask you not to copy, use or disclose it. Please notify this error to the sender immediately and delete this message from your system. Société Air France - Limited company with capital of 126,748,775 euros - Bobigny register of companies (France) 420 495 178 - 45, rue de Paris, Tremblay-en-France, 95747 Roissy Charles de Gaulle CEDEX  Pensez à l'environnement avant d'imprimer ce message.  
Think of the environment before printing this mail.

**Comment by MatthiasVets** [comment]
I'm having the same issue.
Does any body have a solution for this?
In liquibase-core 3.4.1 it seems to be fixed [CORE-2416](https://liquibase.jira.com/browse/CORE-2416).
I also tried to use master version off liquibase-hibernate4 but keep getting this behaviour.

**Comment by nvoxland** [comment]
Fixed in liquibase 3.5.2 under by CORE-2855
