### ISSUE TITLE
autoIncrement="true" should not be set for Char and UUID types, Hibernate 4.3

### ISSUE THREAD

**Issue by talklittle** [liquibase/liquibase-hibernate#94]
Followup to #30 

`autoIncrement="true"` is being set for `char(36)` and `UUID` Postgres types, when dealing with `java.util.UUID` primary keys.

Removing the `@GeneratedValue` annotation doesn't help. `liquibase.ext.hibernate.snapshot.ColumnSnapshotGenerator` keeps getting `"native"` as the `identifierGeneratorStrategy`.

    @Id
    @Column
    @Type(type="pg-uuid")
    private UUID id;

**Comment by nvoxland** [comment]
Working for me with earlier changes made to the upcoming liquibase-hibernate 3.6 and liquibase 3.5.2
