### ISSUE TITLE
Running Maven Liquibase-Hibernate diff causes NoSuchMethodError on PrimaryKey.addColumnName

### ISSUE THREAD

**Issue by thangmai** [liquibase/liquibase-hibernate#97]
I got a same issue with using version 3.4 for Hibernate 3.x together with Liquibase 3.3.x and wonder if there is any plan for releasing 3.5 version for Hibernate 3.x?

http://stackoverflow.com/questions/27298770/running-maven-liquibase-hibernate-diff-causes-nosuchmethoderror-on-primarykey-ad

**Comment by nvoxland** [comment]
liquibase-hibernate 3.6 will support Liquibase 3.5.2
