### ISSUE TITLE
Liquibase vs Hibernate Envers

### ISSUE THREAD

**Issue by mmaask** [liquibase/liquibase-hibernate#99]
A solution was done to provide the generation functionality in #27 #54, but this provides just the default table names. These 3 primary field/table names can be altered from JPA configuration properties using these parameters for example:

* org.hibernate.envers.audit_table_suffix: _history
* org.hibernate.envers.revision_field_name: revision
* org.hibernate.envers.revision_type_field_name: revision_info

Defaults being: _AUD, REV, REVINFO

Generating diff has no idea about these and is using default values still, which always results in new changesets. Can those properties be implemented to have an affect when generating diff? Or is it not controlled by the plugin at all?

Thanks.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-488) by [Unito](https://www.unito.io/learn-more)

**Comment by Nagendra080389** [comment]
Facing same issue when running on an existing project managed by liquibase. It finds tables, primary keys and foreign keys, but still generates same changesets again. Can this be fixed please?

**Comment by crtk** [comment]
Encountered the same issue.
Workaround for now:
- set `@AuditTable` for audited entities
- create a custom revision entity and...
1.  add a `@Table` name
2. add a custom `@RevisionNumber` field on (in my case it is the same as `@Id`)

**Comment by MalteKrueger** [comment]
I found another workaroud for this problems searching for a solution to set org.hibernate.envers.global_with_modified_flag and generating diffs with maven.

You can set envers (and probably others too) properties via the environment (i.e. -Dorg.hibernate.envers.global_with_modified_flag=true). Audit_table_prefix and audit_table_sufix also worked.
